# Cleaning Lyrics Data

This lyrics data cleaning used to correct the wrong lyrics pulled in by Lyrics Genius API. This happened because their is inconsistency in the way some track name and artist name appear in Lyrics Genius and how they appear in Spotify. Two functions were created for cleaning and another two for pulling the lyrics. Two to check for wrong lyrics by counting the number of times the track name appear in the lyrics and the other to check if it contains data and the word "feat". This was the most stressful and time consuming part of my work, because even after cleaning I had to maually do it myself.

# Load Datasets

This dataset were loaded from the dataset in Lyrics and Musical Feature Data Collection Notebook

In [2]:
import re
import pandas as pd
import lyricsgenius as genius

gym = pd.read_csv('/Users/mac/Downloads/Bar.csv')
bedroom = pd.read_csv('/Users/mac/Downloads/Bedroom.csv') 
library = pd.read_csv('/Users/mac/Downloads/Library.csv') 
office = pd.read_csv('/Users/mac/Downloads/Office.csv') 
trainBus = pd.read_csv('/Users/mac/Downloads/TrainBus.csv')
restaurant = pd.read_csv('/Users/mac/Downloads/Restaurant.csv')
bar = pd.read_csv('/Users/mac/Downloads/Bar.csv')
mall = pd.read_csv('/Users/mac/Downloads/Mall.csv')

# Clean Lyrics

In [80]:


api=genius.Genius('lwGgNIQ7ObjCzE1uuDjxOyX5IgUVlcfZBDdG2CAKcBsehFodJiivZz_T23dfrs4J')

def count_title_in_lyrics(track_name, lyrics):
    """
    Count the number of times the cleaned track_name appears in the lyrics.
    """
    # Clean the track name
    cleaned_track_name = clean_track_name(track_name)
    
    # Convert lyrics to lowercase for case-insensitive comparison
    lyrics_lower = lyrics.lower()
    
    # Count the occurrences of the cleaned track name in the lyrics
    count = lyrics_lower.count(cleaned_track_name)
    
    return count

pattern = re.compile(r"\b\d{2}/\d{2}/\d{2}\b|feat", re.IGNORECASE)

def match_pattern(lyrics):
    return bool(pattern.search(lyrics))


# Function to clean track names by removing remaster suffixes and text within parentheses
def clean_track_name(track_name):
    # First, remove any text within parentheses, including the parentheses themselves
    cleaned_name = re.sub(r'\s*\(.*?\)', '', track_name)
    # Then, remove any " - Year Remaster" or similar suffixes
    cleaned_name = re.sub(r' - \d{4}.*$', '', cleaned_name)
    # Finally, strip any leading or trailing whitespace
    return cleaned_name.strip()

def fetch_lyrics_in_batches(api, df, track_col='track_name', artist_col='artist_name', batch_size=100):
    all_lyrics = []

    # Clean the track names in the DataFrame
    df['cleaned_track_name'] = df[track_col].apply(clean_track_name)

    # Split the track names and artists into batches of up to 100
    tracks = df['cleaned_track_name'].tolist()
    artists = df[artist_col].tolist()

    for i in range(0, len(tracks), batch_size):
        batch_tracks = tracks[i:i + batch_size]
        batch_artists = artists[i:i + batch_size]
        batch_lyrics = []

        for track, artist in zip(batch_tracks, batch_artists):
            try:
                song = api.search_song(title=track, artist=artist)
                if song:
                    lyric = song.lyrics
                    batch_lyrics.append(lyric)
                else:
                    batch_lyrics.append('Lyrics not found')
            except Exception as e:
                print(f'Error fetching lyrics for {track} by {artist}: {str(e)}')
                batch_lyrics.append(f'Error: {str(e)}')

        all_lyrics.extend(batch_lyrics)

    # Append lyrics to the DataFrame
    df['lyrics'] = all_lyrics
    return df

In [185]:
def clean_track_name(track_name):
    """
    Clean the track name by removing any text within parentheses and any suffixes starting with '-'.
    """
    # Remove text within parentheses, including the parentheses
    cleaned_name = re.sub(r'\s*\(.*?\)', '', track_name)
    # Remove any suffix starting with '-'
    cleaned_name = re.sub(r' - .*$', '', cleaned_name)
    # Return the cleaned name with leading and trailing whitespace removed
    return cleaned_name.strip().lower()



def process_lyrics(df, track_col='track_name', lyrics_col='lyrics'):
    """
    Process the DataFrame to count how many times the cleaned track name appears in the lyrics.
    """
    df['word_count'] = df.apply(lambda row: count_title_in_lyrics(row[track_col], row[lyrics_col]), axis=1)
    return df

def show_artist_and_track(df, index):
    """
    Show the artist_name and track_name for a given index in the DataFrame.
    
    Parameters:
    - df: The DataFrame containing the music data.
    - index: The index of the row you want to inspect.
    
    Returns:
    - A tuple containing (artist_name, track_name) if the index is valid.
    - A message indicating the index is out of bounds if the index is invalid.
    """
    if index in df.index:
        artist_name = df.at[index, 'artist_name']
        track_name = df.at[index, 'track_name']
        return artist_name, track_name
    else:
        return f"Index {index} is out of bounds."

## Gym

In [27]:
gym['track_name_count'] = gym.apply(lambda row: row['lyrics'].lower().count(row['track_name'].lower()), axis=1)
gym_wrong_lyrics = gym[gym['track_name_count'] == 0][['track_name', 'artist_name', 'lyrics', 'track_name_count']]

In [40]:
# Fetch lyrics for wrong gym lyrics
fetch_lyrics_in_batches(api, gym_wrong_lyrics)

Searching for "HUMBLE." by Kendrick Lamar...
Done.
Searching for "Praise The Lord (Da Shine) (feat. Skepta)" by A$AP Rocky...
Done.
Searching for "Superhero (Heroes & Villains) [with Future & Chris Brown]" by Metro Boomin...
Done.
Searching for "DNA." by Kendrick Lamar...
Error fetching lyrics for DNA. by Kendrick Lamar: Request timed out:
HTTPSConnectionPool(host='genius.com', port=443): Read timed out. (read timeout=5)
Searching for "Hypnotize" by The Notorious B.I.G....
Done.
Searching for "Wild Thoughts (feat. Rihanna & Bryson Tiller)" by DJ Khaled...
Done.
Searching for "INDUSTRY BABY (feat. Jack Harlow)" by Lil Nas X...
Done.
Searching for "Ballin' (with Roddy Ricch)" by Mustard...
Done.
Searching for "Boy's a liar Pt. 2" by PinkPantheress...
Done.
Searching for "Wanna Be (with Megan Thee Stallion & Cardi B) - Remix" by GloRilla...
Done.
Searching for "GEEKALEEK (feat. BIA)" by OHGEESY...
Done.
Searching for "FTCU (feat. Travis Scott, Chris Brown & Sexyy Red) - SLEEZEMIX" by Nicki Minaj...
Done.
Searching for "Bongos (feat. Megan Thee Stallion)" by Cardi B...
Done.
Searching for "Megan's Piano" by Megan Thee Stallion...
Done.
Searching for "Princess Diana (with Nicki Minaj)" by Ice Spice...
Done.
Searching for "Booty Club" by Sandy Cheekz...
Done.
Searching for "SHAKE SUMN (with Sexyy Red) - REMIX" by DaBaby...
Done.
Searching for "SHAKE (feat. Kaliii and Stunna Girl)" by YG...
Done.
Searching for "Peaches & Eggplants (feat. Latto & Sexyy Red)" by Young Nudy...
Done.
Searching for "AIN'T GONNA ANSWER" by NLE Choppa...
Done.
Searching for "All Dere (feat. Moneybagg Yo)" by GloRilla...
Done.
Searching for "We Not Humping - Remix" by Monaleo...
Done.
Searching for "Throw It! - Remix" by Spiffy The Goat...
Done.
Searching for "Pound Town 2 (feat. Nicki Minaj & Tay Keith)" by Sexyy Red...
Done.
Searching for "Keep Dat Nigga (Part 2) (feat. GloRilla, Kali & Big Boss Vette)" by Icandy...
Done.
Searching for "Budget (feat. Latto)" by Megan Thee Stallion...
Done.
Searching for "F.N.F (Let's Go) - Remix" by Hitkidd...
Done.
Searching for "Wild Wild Love (feat. G.R.L.)" by Pitbull...
Done.
Searching for "Tell Me When You Ready (feat. Future)" by Flo Rida...
Done.
Searching for "Five Hours" by Deorro...
Specified song does not contain lyrics. Rejecting.
Searching for "Payback" by Dimitri Vangelis & Wyman...
Specified song does not contain lyrics. Rejecting.
Searching for "I Need Your Love (feat. Ellie Goulding)" by Calvin Harris...
Done.
Searching for "Bad (feat. Vassy) - Radio Edit" by David Guetta...
No results found for: 'Bad (feat. Vassy) - Radio Edit David Guetta'
Searching for "Remember the Name (feat. Styles of Beyond)" by Fort Minor...
Done.
Searching for "King Sh*t (feat. T.I.)" by Yo Gotti...
Done.
Searching for "Till The World Ends (the Femme Fatale Remix) (feat. Nicki Minaj & Ke$ha)" by Britney Spears...
No results found for: 'Till The World Ends (the Femme Fatale Remix) (feat. Nicki Minaj & Ke$ha) Britney Spears'
Searching for "Tonight Is the Night" by Outasight...
Done.
Searching for "Let's Go (feat. Twista & Lil' Jon)" by Trick Daddy...
Done.
Searching for "Bangarang (feat. Sirah)" by Skrillex...
Done.
Searching for "All of Me - Tiësto's Birthday Treatment Remix - Radio Edit" by John Legend...
Done.
Searching for "Jealous (I Ain't With It)" by Chromeo...
Done.
Searching for "Cryin' Like A Bitch!!" by Godsmack...
Done.
Searching for "AmEN! (feat. Lil Uzi Vert and Daryl Palumbo of Glassjaw)" by Bring Me The Horizon...
Done.
Searching for "Werewolf (feat. Bring Me The Horizon)" by Lil Uzi Vert...
Done.
Searching for "Black Wedding (feat. Rob Halford)" by In This Moment...
Done.
Searching for "One Foot In The Grave (feat. Aaron Pauley of Of Mice & Men)" by From Ashes to New...
Done.
Searching for "AFRAID TO DIE (feat. Tatiana Shmayluyk from Jinjer)" by P.O.D....
No results found for: 'AFRAID TO DIE (feat. Tatiana Shmayluyk from Jinjer) P.O.D.'
Searching for "Black Thunder (feat. Serj Tankian and DL of Bad Wolves)" by The HU...
Done.
Searching for "Talk To Me (feat. Lzzy Hale)" by Apocalyptica...
Done.
Searching for "Austin (Boots Stop Workin') - Distant Matter Remix" by Dasha...
Done.
Searching for "Espresso - Mark Ronson x FNZ Working Late Remix" by Sabrina Carpenter...
Done.
Searching for "One Kiss (with Dua Lipa)" by Calvin Harris...
Done.
Searching for "I'm Good (Blue)" by David Guetta...
Done.
Searching for "CONTIGO (with Tiësto)" by KAROL G...
Done.
Searching for "Baby Don't Hurt Me" by David Guetta...
Done.
Searching for "For Life (feat. Nile Rodgers)" by Kygo...
Done.
Searching for "Deep Down (feat. Never Dull)" by Alok...
Done.
Searching for "Friday (feat. Mufasa & Hypeman) - Dopamine Re-Edit" by Riton...
Done.
Searching for "Words (feat. Zara Larsson)" by Alesso...
Done.
Searching for "Desire (with Sam Smith)" by Calvin Harris...
Done.
Searching for "Heaven Takes You Home (feat. Connie Constance)" by Swedish House Mafia...
Done.
Searching for "Man In Finance (with David Guetta)" by David Guetta...
Done.
Searching for "21 Reasons (feat. Ella Henderson)" by Nathan Dawe...
Done.
Searching for "Where Did You Go? (feat. MNEK)" by Jax Jones...
Done.
Searching for "Lovers In A Past Life (with Rag'n'Bone Man)" by Calvin Harris...
Done.
Searching for "Fortnight (feat. Post Malone) - BLOND:ISH Remix" by Taylor Swift...
Done.
Searching for "Makeba - Ian Asher Remix" by Jain...
Done.
Searching for "DNA (Loving You) [feat. Hannah Boleyn]" by Billy Gillies...
Done.
Searching for "SLEEP TONIGHT (THIS IS THE LIFE) - with R3HAB and Sam Feldt" by Switch Disco...
Done.
Searching for "Another Love - Tiësto Remix" by Tom Odell...
Done.
Searching for "I Was Made For Lovin' You (feat. Nile Rodgers & House Gospel Choir)" by Oliver Heldens...
Done.
Searching for "When I’m Gone (with Katy Perry)" by Alesso...
Done.
Searching for "Love Bites (Feat. Tove Lo & SG Lewis)" by Nelly Furtado...
Done.
Searching for "Never Be Lonely - Cascada Remix" by Jax Jones...
Done.
Searching for "Murder On The Dancefloor - David Guetta Remix" by Sophie Ellis-Bextor...
Done.
Searching for "Unstoppable - R3HAB Remix" by Sia...
Done.
Searching for "Under The Sun (with Alok)" by Ella Henderson...
Done.
Searching for "Mi Amor (with JVKE & Anitta)" by Sam Feldt...
Done.
Searching for "Call Me (with R3HAB & Timmy Trumpet)" by Gabry Ponte...
Done.
Searching for "Choose Your Fighter (From Barbie The Album)" by Ava Max...
Done.
Searching for "Dancing On My Own - Tiësto Remix" by Calum Scott...
Done.
Searching for "Only Way Is Up (feat. Izzy Bizu)" by Robin Schulz...
Done.
Searching for "we can't be friends (wait for your love)" by Ariana Grande...
Done.
Searching for "Dance The Night - From Barbie The Album" by Dua Lipa...
Done.
Searching for "Cold Heart - PNAU Remix" by Elton John...
Done.
Searching for "Substitution (feat. Julian Perretta)" by Purple Disco Machine...
Done.
Searching for "CAN'T STOP THE FEELING! (from DreamWorks Animation's "TROLLS")" by Justin Timberlake...
No results found for: 'CAN'T STOP THE FEELING! (from DreamWorks Animation's "TROLLS") Justin Timberlake'
Searching for "HE KNOWS (feat. Lil Nas X)" by Camila Cabello...
Done.
Searching for "INDUSTRY BABY (feat. Jack Harlow)" by Lil Nas X...
Done.
Searching for "Dancing In The Moonlight (feat. NEIMY)" by Jubël...
Done.
Searching for "Taki Taki (with Selena Gomez, Ozuna & Cardi B)" by DJ Snake...
Done.
Searching for "Dancing With A Stranger (with Normani)" by Sam Smith...
Done.
Searching for "Summer of Love (Shawn Mendes & Tainy)" by Shawn Mendes...
Done.
Searching for "Lights - Sped Up Version" by Ellie Goulding...
Done.
Searching for "Lil Bit (feat. Florida Georgia Line)" by Nelly...
Done.
Searching for "Step Back" by Cushy...
Specified song does not contain lyrics. Rejecting.
Searching for "Twenty Ten" by Dylan Sitts...
Specified song does not contain lyrics. Rejecting.
Searching for "Malaku" by Uhrk-Nagimi...
No results found for: 'Malaku Uhrk-Nagimi'
Searching for "Flavah'" by Ganyaman...
Done.
Searching for "Stardestroyer" by Captain XY...
No results found for: 'Stardestroyer Captain XY'
Searching for "Banished" by Geppilef...
No results found for: 'Banished Geppilef'
Searching for "Giggin" by Ballpoint...
Specified song does not contain lyrics. Rejecting.
Searching for "Fairy Pond" by ImLike...
Done.
Searching for "Lasereyes" by Takek...
Done.
Searching for "Respect Me" by Toby Tranter...
Done.
Searching for "Forest of Sin" by Hephisto...
Done.
Searching for "Skullcrusher" by Cushy...
Specified song does not contain lyrics. Rejecting.
Searching for "Nalaar" by Waloox...
Done.
Searching for "24k" by FourFiveNyne...
No results found for: '24k FourFiveNyne'
Searching for "Unimerse" by Push N' Glide...
Done.
Searching for "Geeker" by peerless...
Done.
Searching for "Pollution" by Casiiwool...
No results found for: 'Pollution Casiiwool'
Searching for "LBRTY" by Heyson...
Done.
Searching for "Run the Clock" by Ballpoint...
Specified song does not contain lyrics. Rejecting.
Searching for "Audio Picasso" by mzet...
Done.
Searching for "Hunch" by Azucares...
No results found for: 'Hunch Azucares'
Searching for "Unleashed - Instrumental" by HiveMind...
Done.
Searching for "You Say It's Easy" by Damma Beatz...
Specified song does not contain lyrics. Rejecting.
Searching for "No home no future" by Captain XY...
Done.
Searching for "Willfully Blind" by Nowhere Now Here...
Done.
Searching for "Gold Stacks" by Tatchy...
Done.
Searching for "Brutal Wishes" by Damma Beatz...
Specified song does not contain lyrics. Rejecting.
Searching for "Blood From Stone" by 7hour flower...
No results found for: 'Blood From Stone 7hour flower'
Searching for "Outcast Society" by ZooLoo One...
Done.
Searching for "Ares" by Classe Beats...
Done.
Searching for "Probiotic." by Timothy Infinite...
Specified song does not contain lyrics. Rejecting.
Searching for "Riddle Box" by Hephisto...
Done.
Searching for "Elephants" by Cushy...
Specified song does not contain lyrics. Rejecting.
Searching for "New Tech" by _91nova...
Specified song does not contain lyrics. Rejecting.
Searching for "Reverse Spell" by Takek...
Done.
Searching for "Haute" by BLUE STEEL...
Specified song does not contain lyrics. Rejecting.
Searching for "Failed the Test" by Toby Tranter...
Done.
Searching for "Leo" by D-Platform...
No results found for: 'Leo D-Platform'
Searching for "Life I Live" by Cushy...
Specified song does not contain lyrics. Rejecting.
Searching for "The Riddle of the Record" by Dusty Decks...
Done.
Searching for "Edén" by Nerso & Verse...
Done.
Searching for "Maharajah" by Ava Low...
No results found for: 'Maharajah Ava Low'
Searching for "Y2K" by BLUE STEEL...
Specified song does not contain lyrics. Rejecting.
Searching for "Must Be Lost" by Jharee...
Done.
Searching for "SNATCHIN CROWNS 王位" by Yungmaple...
No results found for: 'SNATCHIN CROWNS 王位 Yungmaple'
Searching for "The Other Side Of Existence" by Yuni Wa...
Done.
Searching for "Sumwhere Else" by Cushy...
Specified song does not contain lyrics. Rejecting.
Searching for "Destroyer" by Cushy...
Specified song does not contain lyrics. Rejecting.
Searching for "Cut a Rug" by Matt Large...
Specified song does not contain lyrics. Rejecting.
Searching for "ELECTRICITY" by BLUE STEEL...
Specified song does not contain lyrics. Rejecting.
Searching for "High-Rise" by _91nova...
Specified song does not contain lyrics. Rejecting.
Searching for "Straight Heat" by Dr. J...
Done.
Searching for "Face It" by Damma Beatz...
Specified song does not contain lyrics. Rejecting.
Searching for "No Switch Up" by A P O L L O...
Done.
Searching for "No Mercy" by Cushy...
Specified song does not contain lyrics. Rejecting.
Searching for "Golden Barb Wire" by OWN A JET...
Done.
Searching for "Homemade Punch" by Confetti Grenade...
Done.
Searching for "Outside Today" by Damma Beatz...
Specified song does not contain lyrics. Rejecting.
Searching for "Bat Caves" by Captain XY...
Done.
Searching for "Theatre of Pain" by Sarach...
Done.
Searching for "Shoyu" by IMANU...
Specified song does not contain lyrics. Rejecting.
Searching for "Cloak and Dagger" by Ballpoint...
Specified song does not contain lyrics. Rejecting.
Searching for "danyyye" by Lukas Got Lucky...
No results found for: 'danyyye Lukas Got Lucky'
Searching for "JOYFUL VS HAPPINESS" by DJ DENZ The Rooster...
No results found for: 'JOYFUL VS HAPPINESS DJ DENZ The Rooster'
Searching for "Sahara - Onderkoffer & Basshoven Remix" by Hensonn...
No results found for: 'Sahara - Onderkoffer & Basshoven Remix Hensonn'
Searching for "Camelot" by Ballpoint...
Specified song does not contain lyrics. Rejecting.
Searching for "Occult" by Ballpoint...
Specified song does not contain lyrics. Rejecting.
Searching for "Top of the Line" by Cushy...
Specified song does not contain lyrics. Rejecting.
Searching for "Wealth" by Nesyu Beats...
No results found for: 'Wealth Nesyu Beats'
Searching for "Suspens Trap Beat" by Origin Studio...
Done.
Searching for "Find Your Own Way" by DJ DENZ The Rooster...
Done.
Searching for "Long Way Back" by Damma Beatz...
Specified song does not contain lyrics. Rejecting.
Searching for "Locked On" by A P O L L O...
Done.
Searching for "Incredulous" by Dylan Sitts...
Specified song does not contain lyrics. Rejecting.
Searching for "Ruckus" by _91nova...
Specified song does not contain lyrics. Rejecting.
Searching for "I'm Not Playing" by Ballpoint...
Specified song does not contain lyrics. Rejecting.
Searching for "Codename" by T33N...
No results found for: 'Codename T33N'
Searching for "Detention" by Dylan Sitts...
Specified song does not contain lyrics. Rejecting.
Searching for "Matrix" by BLUE STEEL...
Specified song does not contain lyrics. Rejecting.
Searching for "Wild World - Acoustic Version" by Joanna Wang...
Done.
Searching for "Gimme Gimme Gimme" by FÄT TONY...
Done.
Searching for "Dernière danse - Techno Mix" by Indila...
Done.
Searching for "Get Busy - Odd Mob Club Mix" by Sean Paul...
Done.
Searching for "i like the way you kiss me - southstar remix" by Artemas...
Done.
Searching for "Couldn't Care Less (feat. Gia Koka)" by ALTÉGO...
Done.
Searching for "Rockafeller Skank" by ILYAA...
No results found for: 'Rockafeller Skank ILYAA'
Searching for "It's That Time - FISHER Remix" by Marlon Hoffstadt...
Done.
Searching for "Vois sur ton chemin - Techno Mix" by BENNETT...
Done.
Searching for "Pedro - W&W Remix" by Jaxomy...
Done.
Searching for "Give It To Me - Full Vocal Mix" by Matt Sassari...
Done.
Searching for "PATT (Party All The Time) - Adam Beyer, Layton Giordani & Green Velvet Remix" by Sharam...
Done.
Searching for "Whatever (with Ava Max) - Tiësto Remix" by Kygo...
Done.
Searching for "Stumblin' In (feat. Timmy Trumpet) [Steve Aoki x Dimatik Remix]" by CYRIL...
Done.
Searching for "OneHundred" by HEDEGAARD...
No results found for: 'OneHundred HEDEGAARD'
Searching for "Techno Cobra" by Raaban...
Done.
Searching for "LET'S GET FKD UP" by Alok...
Done.
Searching for "MONEY ON THE DASH" by Fyex...
Done.
Searching for "Last Night - Anyma x Layton Giordani Remix" by Loofy...
Specified song does not contain lyrics. Rejecting.
Searching for "My Mama Dropped LSD in the 90's" by Marlon Hoffstadt...
Specified song does not contain lyrics. Rejecting.
Searching for "Be My Lover (feat. La Bouche)" by Hypaton...
Done.
Searching for "Go Back (feat. Julia Church)" by John Summit...
Done.
Searching for "Tell Me Why - MEDUZA Remix" by Supermode...
Done.
Searching for "Drums (Feat. Kim Petras)" by James Hype...
Done.
Searching for "Like A G6 (with Naeleck)" by Timmy Trumpet...
Done.
Searching for "Sweet Disposition - John Summit & Silver Panda Remix" by The Temper Trap...
Done.
Searching for "Lay All Your Love On Me" by loafers...
Done.
Searching for "Tattoo - Topic Remix" by Loreen...
Done.
Searching for "Turn On The Lights again.. (feat. Future & Fred again..) - Anyma Remix" by Swedish House Mafia...
Done.
Searching for "Rock My Body (with Sash!) - W&W x R3HAB VIP Remix" by R3HAB...
No results found for: 'Rock My Body (with Sash!) - W&W x R3HAB VIP Remix R3HAB'
Searching for "PARADISE" by HI-LO...
Specified song does not contain lyrics. Rejecting.

,track_name,artist_name,lyrics,track_name_count,cleaned_track_name
6,HUMBLE.,Kendrick Lamar,1016 ContributorsTranslationsTürkçeEspañolРусс...,0,HUMBLE.
11,Praise The Lord (Da Shine) (feat. Skepta),A$AP Rocky,172 ContributorsRanking Page: 50 Best Albums &...,0,Praise The Lord (Da Shine) (feat. Skepta)
14,Superhero (Heroes & Villains) [with Future & C...,Metro Boomin,1 Contributor2018 haywoodindahood Listening Lo...,0,Superhero (Heroes & Villains) [with Future & C...
19,DNA.,Kendrick Lamar,Error: Request timed out:\nHTTPSConnectionPool...,0,DNA.
22,Hypnotize - 2014 Remaster,The Notorious B.I.G.,228 ContributorsHypnotize Lyrics[Intro: The No...,0,Hypnotize
...,...,...,...,...,...
577,Lay All Your Love On Me,loafers,3 ContributorsThe Beginning. The Separation. L...,0,Lay All Your Love On Me
579,Tattoo - Topic Remix,Loreen,1 ContributorTattoo (Topic Remix) Lyrics[Verse...,0,Tattoo - Topic Remix
581,Turn On The Lights again.. (feat. Future & Fre...,Swedish House Mafia,3 ContributorsTurn On The Lights again.. (Anym...,0,Turn On The Lights again.. (feat. Future & Fre...
592,Rock My Body (with Sash!) - W&W x R3HAB VIP Remix,R3HAB,Lyrics not found,0,Rock My Body (with Sash!) - W&W x R3HAB VIP Remix
593,PARADISE,HI-LO,Lyrics not found,0,PARADISE

In [57]:
from lyricsgenius import Genius

def fetch_lyrics(api, track_name, artist_name):
    """
    Fetches lyrics for a given track name and artist name using the Genius API.
    
    Parameters:
    - api: The Genius API client.
    - track_name: The name of the track.
    - artist_name: The name of the artist.
    
    Returns:
    - lyrics: The lyrics of the song if found, otherwise an appropriate message.
    """
    try:
        # Search for the song using the Genius API
        song = api.search_song(title=track_name, artist=artist_name)
        if song:
            return f"Lyrics for '{track_name}' by {artist_name}:\n\n{song.lyrics}"
        else:
            return f"Lyrics for '{track_name}' by {artist_name} not found."
    except Exception as e:
        return f"An error occurred: {str(e)}"



gym_11 = fetch_lyrics(api, track_name = "Praise the Lord (Da Shine)", artist_name = "A$AP Rocky")
gym_14 = fetch_lyrics(api, track_name = "Superhero (Heroes & Villains)",
                      artist_name = "Metro Boomin, Future & Chris Brown")
gym_19 = fetch_lyrics(api, track_name = "DNA.",
                      artist_name = "Kendrick Lamar")
gym_27 = fetch_lyrics(api, track_name = "Wild Thoughts", artist_name = "DJ Khaled")
gym_45 = fetch_lyrics(api, track_name = "Ballin'", artist_name = "Mustard")
gym_53 = fetch_lyrics(api, track_name = "Wanna Be'", artist_name = "GloRilla")

In [107]:
gym.loc[11, 'lyrics'] = gym_11
gym.loc[19, 'lyrics'] = gym_19
gym.loc[27, 'lyrics'] = gym_27
gym.loc[45, 'lyrics'] = gym_45
gym.loc[53, 'lyrics'] = gym_53
gym.loc[14, 'lyrics'] = gym_14

In [224]:
gym_6 = fetch_lyrics(api, track_name = "HUMBLE.", artist_name = "Kendrick Lamar")
gym_113 = fetch_lyrics(api, track_name = "King Shit", artist_name = "Yo Gotti")
gym_115 = fetch_lyrics(api, track_name = "Tonight Is the Night", artist_name = "Outasight")
gym_226 = fetch_lyrics(api, track_name = "Austin (Boots Stop Workin’)", artist_name = "Dasha")
gym_285 = fetch_lyrics(api, track_name = "SLEEP TONIGHT (THIS IS THE LIFE)", artist_name = "Switch Disco")
gym_338 = fetch_lyrics(api, track_name = "Dance The Night", artist_name = "Dua Lipa")
gym_527 = fetch_lyrics(api, track_name = "Wild World", artist_name = "王若琳 (Joanna Wang)")
gym_533 = fetch_lyrics(api, track_name = "Get Busy", artist_name = "Sean Paul")
gym_544 = 'Yo paseaba sola por las calles Sacando fotos a los monumentos La típica extranjera con un aire extraño \
Que recorre entera toda la ciudad'
gym_547 = fetch_lyrics(api, track_name = "Whatever (Tiësto Remix)", artist_name = "Kygo & Ava Max")
gym_567 = fetch_lyrics(api, track_name = "Like A G6", artist_name = "Timmy Trumpet & POLTERGST")
gym_581 = fetch_lyrics(api, track_name = "Turn On The Lights again..", artist_name = "Fred again.. & Swedish House Mafia")

Searching for "HUMBLE." by Kendrick Lamar...
Done.

In [314]:
gym.loc[6, 'lyrics'] = gym_6
gym.loc[113, 'lyrics'] = gym_113
gym.loc[115, 'lyrics'] = gym_115
gym.loc[226, 'lyrics'] = gym_226
gym.loc[285, 'lyrics'] = gym_285
gym.loc[338, 'lyrics'] = gym_338
gym.loc[527, 'lyrics'] = gym_527
gym.loc[533, 'lyrics'] = gym_533
gym.loc[544, 'lyrics'] = gym_544
gym.loc[547, 'lyrics'] = gym_547
gym.loc[567, 'lyrics'] = gym_567
gym.loc[581, 'lyrics'] = gym_581

## Bar

In [320]:
bar['track_name_count'] = bar.apply(lambda row: row['lyrics'].lower().count(row['track_name'].lower()), axis=1)
new_bar = bar[bar['track_name_count'] == 0][['track_name', 'artist_name', 'lyrics', 'track_name_count']]
new_bar=new_bar[new_bar['lyrics'] != 'Lyrics not found']

new_bar = process_lyrics(new_bar)
new_new_bar=new_bar[new_bar['lyrics'] != 'Lyrics not found']

In [332]:
fetch_lyrics_in_batches(api, new_bar)

Searching for "body" by Loud Luxury...
Done.
Searching for "talk" by Khalid...
Done.
Searching for "cold" by Maroon 5...
Done.
Searching for "attention" by Charlie Puth...
Done.
Searching for "heatstroke" by Calvin Harris...
Done.
Searching for "rockabye" by Clean Bandit...
Done.
Searching for "lost in japan" by Shawn Mendes...
Done.
Searching for "god's plan" by Drake...
Done.
Searching for "circles" by Post Malone...
Done.
Searching for "what lovers do" by Maroon 5...
Done.
Searching for "bad at love" by Halsey...
Done.
Searching for "havana" by Camila Cabello...
Done.
Searching for "the weekend" by SZA...
Done.
Searching for "playinwitme" by KYLE...
Done.
Searching for "moves like jagger" by Maroon 5...
Done.
Searching for "love yourself" by Justin Bieber...
Done.
Searching for "cold water" by Major Lazer...
Done.
Searching for "i took a pill in ibiza" by Mike Posner...
Done.
Searching for "congratulations" by Post Malone...
Done.
Searching for "feels" by Calvin Harris...
Done.
Searching for "whenever" by Kris Kross Amsterdam...
Done.
Searching for "honey, i'm good." by Andy Grammer...
Done.
Searching for "fishing in the dark" by Nitty Gritty Dirt Band...
Done.
Searching for "she's in love with the boy" by Trisha Yearwood...
Done.
Searching for "jolene" by Dolly Parton...
Done.
Searching for "867-5309 / jenny" by Tommy Tutone...
Done.
Searching for "high school never ends" by Bowling For Soup...
Done.
Searching for "sugar, we're goin down" by Fall Out Boy...
Done.
Searching for "she will be loved" by Maroon 5...
Done.
Searching for "uptown funk" by Mark Ronson...
Done.
Searching for "everybody" by Backstreet Boys...
Done.
Searching for "nothin' but a good time" by Poison...
Done.
Searching for "you oughta know" by Alanis Morissette...
Done.
Searching for "what's up?" by 4 Non Blondes...
Done.
Searching for "self esteem" by Wild Tales...
Done.
Searching for "she hates me" by Pacific Edge...
Done.
Searching for "xxx's and ooo's" by Trisha Yearwood...
Done.
Searching for "even though i'm leaving" by Luke Combs...
Done.
Searching for "10,000 hours" by Dan + Shay...
Done.
Searching for "lose you to love me" by Selena Gomez...
Done.
Searching for "take on me" by 80s Super Hits...
Done.
Searching for "i love rock 'n roll" by Joan Jett & the Blackhearts...
Done.
Searching for "picture" by Kid Rock...
Done.
Searching for "superstition" by Stevie Wonder...
Done.
Searching for "never gonna give you up" by Rick Astley...
Done.
Searching for "good times" by CHIC...
Done.
Searching for "he's the greatest dancer" by Sister Sledge...
Done.
Searching for "faith" by George Michael...
Done.
Searching for "freedom! '90" by George Michael...
Done.
Searching for "let's dance" by David Bowie...
Done.
Searching for "fame" by David Bowie...
Done.
Searching for "make luv" by Room 5...
Done.
Searching for "disco inferno" by The Trammps...
Done.
Searching for "praise you" by Fatboy Slim...
Done.
Searching for "ms. jackson" by Outkast...
Done.
Searching for "wake me up" by Avicii...
Done.
Searching for "sweet lovin'" by Sigala...
Done.
Searching for "you don't know me" by Jax Jones...
Done.
Searching for "don't you know" by Kungs...
Done.
Searching for "blue monday" by New Order...
Done.
Searching for "these days" by Rudimental...
Done.
Searching for "despacito" by Luis Fonsi...
Done.
Searching for "bailando" by Enrique Iglesias...
Done.
Searching for "calma" by Pedro Capó...
Done.
Searching for "i like the way" by Bodyrockers...
Done.
Searching for "grease" by Frankie Valli...
Done.
Searching for "old town road" by Lil Nas X...
Error fetching lyrics for old town road by Lil Nas X: Request timed out:
HTTPSConnectionPool(host='genius.com', port=443): Read timed out. (read timeout=5)
Searching for "sugar" by Robin Schulz...
Done.
Searching for "starlight" by The Supermen Lovers...
Done.
Searching for "get lucky [feat. pharrell williams and nile rodgers]" by Daft Punk...
Done.
Searching for "around the world" by Daft Punk...
Done.
Searching for "one more time" by Daft Punk...
Done.
Searching for "music sounds better with you" by Stardust...
Done.
Searching for "turn around" by Phats & Small...
Done.
Searching for "this girl" by Kungs...
Done.
Searching for "would i lie to you" by David Guetta...
Done.
Searching for "can't hold us" by Macklemore & Ryan Lewis...
Done.
Searching for "don't worry" by Madcon...
Done.
Searching for "glow" by Madcon...
Done.
Searching for "because you move me" by Tinlicker...
Done.
Searching for "devil in me" by Purple Disco Machine...
Done.
Searching for "dye my hair" by ALMA...
Done.
Searching for "flames" by David Guetta...
Done.
Searching for "mad love" by Mabel...
Done.
Searching for "you don't know me" by Jax Jones...
Done.
Searching for "day 'n' nite" by Stefy De Cicco...
Done.
Searching for "blame" by Calvin Harris...
Done.
Searching for "feel the love" by Rudimental...
Done.
Searching for "not giving in" by Rudimental...
Done.
Searching for "don't call me up" by Mabel...
Done.
Searching for "one day" by Bakermat...
Done.
Searching for "i wanna feel" by Secondcity...
Done.
Searching for "roses" by SAINt JHN...
Done.
Searching for "turn me on" by Riton...
Done.
Searching for "all this" by Jay Pryor...
Done.
Searching for "don’t need love" by 220 KID...
Done.
Searching for "gecko" by Oliver Heldens...
Specified song does not contain lyrics. Rejecting.
Searching for "the weekend" by Michael Gray...
Done.
Searching for "pjanoo" by Eric Prydz...
Specified song does not contain lyrics. Rejecting.
Searching for "no superstar" by Giorgio Gee...
Done.
Searching for "hits 2021" by Trinix Remix...
Done.
Searching for "never going home" by Kungs...
Done.
Searching for "for the same man" by B Beat Girls...
Done.
Searching for "yeah yeah yeah" by Jax Jones...
Done.
Searching for "in my zone" by Xoro...
Done.
Searching for "down under" by Luude...
Done.
Searching for "give it to me" by Matt Sassari...
Done.
Searching for "i gotta let u go" by Dominica...
Done.
Searching for "24 hour trips" by Rossi....
Done.
Searching for "california dreamin'" by Chris Lorenzo...
Done.
Searching for "put a record on" by Matt Sassari...
Done.
Searching for "i want you" by Carl Cox...
Done.
Searching for "ain't nobody" by Garreth Maher...
Done.
Searching for "love city" by ELOQ...
Done.
Searching for "beautiful people" by Barbara Tucker...
Done.
Searching for "together onetime" by Dole & Kom...
Done.
Searching for "answer me" by Hans Ulrik...
Done.
Searching for "on late nights" by Snorre Kirk...
Done.
Searching for "woodwind" by Jan Harbeck Quartet...
Done.
Searching for "so tender" by Keith Jarrett...
Done.
Searching for "search for peace" by Jim Snidero...
Done.
Searching for "a flower is a lovesome thing" by Gathering in Jazz...
Error fetching lyrics for a flower is a lovesome thing by Gathering in Jazz: Request timed out:
HTTPSConnectionPool(host='genius.com', port=443): Read timed out. (read timeout=5)
Searching for "this is our year" by Thomas Sejthen Trio...
Done.
Searching for "theme for laura" by Magnus Lindgren...
Done.
Searching for "blue in green" by Chris Botti...
Done.
Searching for "does the sun really shine on the moon" by Marcus Bartelt...
Done.
Searching for "largo" by Portraits in Jazz...
Done.
Searching for "the peacocks" by John Engels...
Done.
Searching for "moondial" by Pat Metheny...
Done.
Searching for "you don't know what love is" by Rasmus H Thomsen Trio...
Done.
Searching for "my funny valentine" by Ben Webster...
Done.
Searching for "strands" by Jakob Bro...
Done.
Searching for "end music" by Portraits in Jazz...
Done.
Searching for "beautiful love" by Rasmus H Thomsen Trio...
Done.
Searching for "lament" by Romain Pilon...
Done.
Searching for "avec le temps" by Giovanni Guidi...
Done.
Searching for "trilly" by Giovanni Guidi Trio...
Specified song does not contain lyrics. Rejecting.
Searching for "twelve for j." by Caris Hermes...
Done.
Searching for "end music" by Nikolaj Hess...
Done.
Searching for "swept away" by Marc Johnson...
Done.
Searching for "search for peace" by Eric Reed...
Done.
Searching for "in a sentimental mood" by Rob Van Bavel...
Done.
Searching for "where do you go?" by Cornelia Nilsson...
Done.
Searching for "it never entered my mind" by Eddie Henderson...
Done.
Searching for "parole parole" by Moulin Roty Trio...
Done.
Searching for "angel eyes" by Rasmus H Thomsen Trio...
Done.
Searching for "blue sunday" by Gathering in Jazz...
Done.
Searching for "life and death" by Avishai Cohen...
Done.
Searching for "three sisters" by Shalosh...
Done.
Searching for "blues after dark" by Benny Golson...
Done.
Searching for "my one and only love" by Mellow In Blue...
Done.
Searching for "isabela" by Oded Tzur...
Done.
Searching for "miss b." by Mu Quintet...
Done.
Searching for "all the things you are" by Sentimental Mood Trio...
Done.
Searching for "slow down look around" by Chip Wickham...
Done.
Searching for "quiet corner" by Shalosh...
Done.
Searching for "where are you?" by Kevin Fort...
Done.
Searching for "you've changed" by Mellow In Blue...
Done.
Searching for "where do we go from here" by Benjamin Lackner...
Done.
Searching for "him, a bull? ha! a bird" by The New York Second...
Done.
Searching for "seeds of change" by Joe Lovano...
Done.
Searching for "slow hot wind" by Jeremy Pelt...
Done.
Searching for "in two minds" by Jerry Lu...
Done.
Searching for "willow weep for me" by Sam Levine...
Done.
Searching for "close enough for love" by Juraj Stanik Trio...
Done.
Searching for "theme for ernie" by Bévort 3...
Done.
Searching for "song to an old friend" by Jakob Bro...
Done.
Searching for "i love music" by Jeremy Pelt...
Done.
Searching for "one step at a time" by Jan Harbeck Quartet...
Done.
Searching for "heroes" by Lynne Arriale Trio...
Done.

,track_name,artist_name,lyrics,track_name_count,word_count,cleaned_track_name
1,Body (feat. brando),Loud Luxury,"56 ContributorsBody Lyrics[Verse 1]\nBabe, don...",0,2,body
3,Talk (feat. Disclosure),Khalid,86 ContributorsTranslationsفارسیEspañolTalk Ly...,0,1,talk
5,Cold (feat. Future),Maroon 5,83 ContributorsTranslationsPortuguêsCold Lyric...,0,3,cold
8,Attention - Oliver Heldens Remix,Charlie Puth,140 ContributorsTranslationsEestiالعربيةEspaño...,0,16,attention
9,"Heatstroke (feat. Young Thug, Pharrell William...",Calvin Harris,96 ContributorsTranslationsEnglishHeatstroke L...,0,1,heatstroke
...,...,...,...,...,...,...
474,Theme for Ernie,Bévort 3,8 ContributorsPalm Pilot Lyrics[Skit]\n*Young ...,0,0,theme for ernie
477,Song To An Old Friend,Jakob Bro,31 ContributorsUlysses (Chap. 12 - Cyclops) Ly...,0,0,song to an old friend
478,I Love Music,Jeremy Pelt,"1 ContributorBaby Talk LyricsNARRATOR: Kids, i...",0,0,i love music
480,One Step at a Time,Jan Harbeck Quartet,7 ContributorsThe Making of Paul (Chap. 4: Pau...,0,0,one step at a time
482,Heroes,Lynne Arriale Trio,5 ContributorsFinnegan’s Wake (Chap. 2.2) Lyri...,0,0,heroes

In [466]:
bar_169 = fetch_lyrics(api, track_name = "She Hates Me", artist_name = "Puddle of Mudd")
bar_191 = fetch_lyrics(api, track_name = "Take on Me", artist_name = "a-ha")
bar_255 = fetch_lyrics(api, track_name = "Old Town Road (Remix)", artist_name = "Lil Nas X")
bar_323 = fetch_lyrics(api, track_name = "One Day (Vandaag)", artist_name = "Bakermat")
bar_333 = fetch_lyrics(api, track_name = "Don’t Need Love", artist_name = "220 KID & GRACEY")
bar_368 = fetch_lyrics(api, track_name = "Gotta Let You Go (Original ’95 Club Mix)", artist_name = "Dominica")

Searching for "She Hates Me" by Puddle of Mudd...
Done.

In [473]:
new_bar.loc[169, 'lyrics'] = bar_169
new_bar.loc[191, 'lyrics'] = bar_191
new_bar.loc[255, 'lyrics'] = bar_255
new_bar.loc[323, 'lyrics'] = bar_323
bar.loc[333, 'lyrics'] = bar_333
new_bar.loc[368, 'lyrics'] = bar_368

## Bedroom

In [483]:
bedroom['track_name_count'] = bar.apply(lambda row: row['lyrics'].lower().count(row['track_name'].lower()), axis=1)
new_bed = bedroom[bedroom['track_name_count'] == 0][['track_name', 'artist_name', 'lyrics', 'track_name_count']]
new_bed=new_bed[new_bed['lyrics'] != 'Lyrics not found']

new_bed = process_lyrics(new_bed)

new_new_bed=new_bed[new_bed['lyrics'] != 'Lyrics not found']

In [485]:
fetch_lyrics_in_batches(api, new_bed)

Searching for "blow [feat. kilo ali]" by Sosa UK...
Done.
Searching for "waiting for tonight" by FISHER...
Done.
Searching for "she's in the club" by MK...
Done.
Searching for "girl$" by Dom Dolla...
Done.
Searching for "all that you need" by Gorgon City...
Done.
Searching for "wild" by James Hype...
Done.
Searching for "lobster telephone" by Peggy Gou...
Done.
Searching for "delirious" by Leftwing : Kody...
Done.
Searching for "under my feet" by Selena Faider...
Done.
Searching for "incanto" by Ryan Arnold...
Done.
Searching for "lemonade" by Deeper Purpose...
Done.
Searching for "to l.a" by Tita Lau...
Done.
Searching for "in your arms" by Jess Bays...
Done.
Searching for "the weekend" by Anti Up...
Done.
Searching for "vibrate" by James Hype...
Done.
Searching for "anthem" by Diplo...
Done.
Searching for "one by one" by Deeper Purpose...
Done.
Searching for "desire" by Chris Stussy...
Done.
Searching for "kissin' on my tattoos" by August Alsina...
Done.
Searching for "2012" by Chris Brown...
Done.
Searching for "you" by Jacquees...
Done.
Searching for "side chick" by Alkaline...
Done.
Searching for "or nah" by Ty Dolla $ign...
Done.
Searching for "planez" by Jeremih...
Done.
Searching for "brown sugar" by D'Angelo...
Done.
Searching for "been that way" by Bryson Tiller...
Done.
Searching for "hit different" by SZA...
Done.
Searching for "sexual healing" by Marvin Gaye...
Done.
Searching for "how you gonna act like that" by Tyrese...
Done.
Searching for "under the influence" by Chris Brown...
Done.
Searching for "no bs" by Chris Brown...
Done.
Searching for "that's what it's made for" by USHER...
Done.
Searching for "mbangu te" by Ya Levis...
Done.
Searching for "up to you" by Chris Brown...
Done.
Searching for "do u wanna" by Donell Jones...
Done.
Searching for "have it all" by Xian Bell...
Done.
Searching for "where i wanna be" by Donell Jones...
Done.
Searching for "body on me" by Ashanti...
Done.
Searching for "you don't know me" by Armand Van Helden...
Done.
Searching for "piece of me" by MK...
Done.
Searching for "wish you were mine" by Philip George...
Done.
Searching for "climbin'" by Shadow Child...
Done.
Searching for "real life" by Duke Dumont...
Done.
Searching for "all night" by Joel Corry...
Done.
Searching for "baby" by Bakermat...
Done.
Searching for "the party" by Joe Stone...
Done.
Searching for "ejaculate" by Mason Maynard...
Done.
Searching for "friday" by Shadow Child...
Done.
Searching for "honey" by 070 Shake...
Done.
Searching for "i went too far" by AURORA...
Done.
Searching for "can't stop" by Red Hot Chili Peppers...
Done.
Searching for "every little step" by Garreth Maher...
Done.
Searching for "gecko" by Oliver Heldens...
Specified song does not contain lyrics. Rejecting.
Searching for "in arms" by Ferreck Dawn...
Done.
Searching for "show me" by Ryan Blyth...
Done.
Searching for "bump & grind" by Vato Gonzalez...
Done.
Searching for "talk to me" by Chasing Abbey...
Done.
Searching for "cola" by CamelPhat...
Done.
Searching for "into my life" by Mark Knight...
Done.
Searching for "no words" by Dave...
Done.
Searching for "piece of me" by MK...
Done.
Searching for "move out of my way" by Dennis Quin...
Done.
Searching for "lonely" by Friend Within...
Done.
Searching for "ketamine" by Versatile...
Done.
Searching for "zeze" by Kodak Black...
Done.
Searching for "back & forth" by MK...
Done.
Searching for "along came polly" by Rebūke...
Specified song does not contain lyrics. Rejecting.
Searching for "my breath" by Adam K...
Done.
Searching for "gypsy woman" by Crystal Waters...
Done.
Searching for "plastic dreams" by Jaydee...
Done.
Searching for "white noise" by Disclosure...
Done.
Searching for "wish you well" by Sigala...
Done.
Searching for "make me feel" by Bellaire...
Done.
Searching for "child" by George FitzGerald...
Done.
Searching for "oh woman oh man" by London Grammar...
Done.
Searching for "lip gloss" by Lil Mama...
Done.
Searching for "i'll be there for you" by The Rembrandts...
Done.
Searching for "can't stop dancin'" by Becky G...
Done.
Searching for "i choose you" by Sara Bareilles...
Done.
Searching for "always be my baby" by Mariah Carey...
Done.
Searching for "how will i know" by Whitney Houston...
Done.
Searching for "love song" by Sara Bareilles...
Done.
Searching for "believe" by Cher...
Done.
Searching for "baby" by Justin Bieber...
Done.
Searching for "london bridge" by Fergie...
Done.
Searching for "can't take my eyes off you" by Frankie Valli...
Done.
Searching for "baby, i love your way" by Big Mountain...
Done.
Searching for "mamma mia" by ABBA...
Done.
Searching for "footloose" by Kenny Loggins...
Done.
Searching for "everything" by Michael Bublé...
Done.
Searching for "marry you" by Bruno Mars...
Done.
Searching for "sunday candy" by Nico Segal...
Done.
Searching for "she's so high" by Tal Bachman...
Done.
Searching for "beautiful girls" by Sean Kingston...
Done.
Searching for "fergalicious" by Fergie...
Done.
Searching for "love on top" by Beyoncé...
Done.
Searching for "u can't touch this" by MC Hammer...
Done.
Searching for "be my baby" by The Ronettes...
Done.
Searching for "ain't it fun" by Paramore...
Done.
Searching for "dancing in the moonlight" by Toploader...
Done.
Searching for "waterfalls" by TLC...
Done.
Searching for "super bass" by Nicki Minaj...
Done.
Searching for "jumpin', jumpin'" by Destiny's Child...
Done.
Searching for "unwritten" by Natasha Bedingfield...
Done.
Searching for "xo" by Beyoncé...
Done.
Searching for "work it" by Missy Elliott...
Done.
Searching for "with you" by Chris Brown...
Done.
Searching for "jordan belfort" by Wes Walker...
Done.
Searching for "beautiful soul" by Jesse McCartney...
Done.
Searching for "bartender" by T-Pain...
Done.
Searching for "lucky" by Jason Mraz...
Done.
Searching for "no air" by Jordin Sparks...
Done.
Searching for "nothin' on you" by B.o.B...
Done.
Searching for "teenage dream" by Katy Perry...
Done.
Searching for "nothing but trouble" by Lil Wayne...
Done.
Searching for "ugly heart" by G.R.L....
Done.
Searching for "my girl" by The Temptations...
Done.
Searching for "i think i'm in love" by Kat Dahlia...
Done.
Searching for "everybody" by Backstreet Boys...
Done.
Searching for "oops!...i did it again" by Britney Spears...
Done.
Searching for "if i were a boy" by Beyoncé...
Done.
Searching for "the way you make me feel" by Michael Jackson...
Done.
Searching for "hot n cold" by Katy Perry...
Done.
Searching for "i wanna dance with somebody" by Whitney Houston...
Done.
Searching for "womanizer" by Britney Spears...
Done.
Searching for "party in the u.s.a." by Miley Cyrus...
Done.
Searching for "***flawless" by Beyoncé...
Done.
Searching for "church bells" by Carrie Underwood...
Done.
Searching for "complicated" by Avril Lavigne...
Done.
Searching for "drops of jupiter" by Train...
Done.
Searching for "hips don't lie" by Shakira...
Done.
Searching for "kiss me thru the phone" by Soulja Boy...
Done.
Searching for "2 on" by Tinashe...
Done.
Searching for "you give love a bad name" by Bon Jovi...
Done.
Searching for "she’s gone, dance on" by Disclosure...
Done.
Searching for "summertime blues" by Chris Lake...
Done.
Searching for "planet blue" by Carlita...
Done.
Searching for "baddy on the floor" by Jamie xx...
Done.
Searching for "get busy" by Sean Paul...
Done.
Searching for "hey boy hey girl" by The Chemical Brothers...
Done.
Searching for "lights out" by Max Styler...
Done.
Searching for "bandit" by Don Toliver...
Done.
Searching for "ride or die" by Aluna...
Done.
Searching for "all my friends are hot" by Jackie Hollander...
Done.
Searching for "vent" by NOIT...
Done.
Searching for "happier" by The Blessed Madonna...
Done.
Searching for "eat the bass" by John Summit...
Done.
Searching for "rizz" by AYYBO...
Done.
Searching for "it's that time" by Marlon Hoffstadt...
Done.
Searching for "me me me" by Catz 'n Dogz...
Done.
Searching for "nanana" by Peggy Gou...
Done.
Searching for "saving up" by Dom Dolla...
Done.
Searching for "atmosphere" by FISHER...
Done.
Searching for "rainfall" by Tom Santa...
Done.
Searching for "sunshine" by Wuki...
Done.
Searching for "feel it" by Floorplan...
Done.
Searching for "fortnight" by Taylor Swift...
Done.
Searching for "how you feel" by ANOTR...
Done.
Searching for "all night long" by Kungs...
Done.
Searching for "weak" by Vintage Culture...
Done.
Searching for "the boy is mine" by James Mac...
Done.
Searching for "body moving" by Eliza Rose...
Done.
Searching for "jamming" by Bob Marley & The Wailers...
Done.
Searching for "last night" by Loofy...
Done.
Searching for "don't you cry" by Sunday Scaries...
Done.
Searching for "your love" by The Outfield...
Done.
Searching for "cruel summer" by Taylor Swift...
Done.
Searching for "stay high" by Diplo...
Done.
Searching for "more baby" by Chris Lake...
Done.
Searching for "more love" by Moderat...
Done.
Searching for "taka" by Ahadadream...
Done.
Searching for "life lesson" by Belters Only...
Done.
Searching for "beats for the underground" by Mau P...
Done.
Searching for "jealous" by Mochakk...
Done.
Searching for "1+1=11" by Peggy Gou...
Specified song does not contain lyrics. Rejecting.
Searching for "low rider" by War...
Done.
Searching for "saving flowers" by salute...
Done.
Searching for "ti sento" by Bob Sinclar...
Done.
Searching for "blue berries" by Sem Jacobs...
Done.
Searching for "i got nothing" by MEDUZA...
Done.
Searching for "brighter days" by Cajmere...
Done.
Searching for "find a way" by Vintage Culture...
Done.
Searching for "can't play myself" by Skepta...
Done.
Searching for "heaven or not" by Diplo...
Done.
Searching for "fine fine baby" by Jamie Jones...
Done.
Searching for "down low" by it's murph...
Done.
Searching for "no sleep" by Matroda...
Done.
Searching for "skip" by Sebastian Ingrosso...
Done.
Searching for "stay together [feat. vula]" by Joel Corry...
Done.
Searching for "biggest regret" by Gorgon City...
Done.
Searching for "needle on the record" by Riordan...
Done.
Searching for "bitch, don't kill my vibe" by Trace...
Done.
Searching for "love on you" by The Magician...
Done.
Searching for "carry me higher" by The Blessed Madonna...
Done.
Searching for "good for you" by Dimitri Vegas...
Done.
Searching for "lady" by Mark Knight...
Done.
Searching for "to the beat" by Cloonee...
Done.
Searching for "lo que soy" by Wax Motif...
Done.
Searching for "monaco" by Blank Sense...
Done.
Searching for "count on my love" by The Blessed Madonna...
Done.
Searching for "feel" by LP Giobbi...
Done.
Searching for "best life" by Ben Böhmer...
Done.

,track_name,artist_name,lyrics,track_name_count,word_count,cleaned_track_name
1,BLOW (WHITE GIRL IN TOWN) [feat. Kilo Ali],Sosa UK,3 ContributorsBLOW (WHITE GIRL IN TOWN) Lyrics...,0.0,0,blow [feat. kilo ali]
3,Waiting For Tonight,FISHER,5 ContributorsWaiting for Tonight Lyrics[Choru...,0.0,14,waiting for tonight
5,She's In The Club (feat. Asal),MK,5 ContributorsShe’s In the Club Lyrics[Verse 1...,0.0,8,she's in the club
8,girl$,Dom Dolla,"5 Contributors​girl$ Lyrics[Intro]\nWoah\nHey,...",0.0,1,girl$
9,All That You Need (feat. Caroline Byrne),Gorgon City,3 ContributorsAll That You Need Lyrics[Intro]\...,0.0,3,all that you need
...,...,...,...,...,...,...
476,Lo Que Soy,Wax Motif,"3 ContributorsLo Que Soy Lyrics[Letra de ""Lo Q...",0.0,16,lo que soy
477,Monaco,Blank Sense,9 ContributorsForeign Kix Lyrics[Chorus: Erick...,0.0,0,monaco
479,Count On My Love,The Blessed Madonna,4 ContributorsCount On My Love Lyrics[Verse]\n...,0.0,7,count on my love
482,Feel,LP Giobbi,3 ContributorsFeel LyricsOh I need this feel f...,0.0,16,feel
483,Best Life,Ben Böhmer,4 ContributorsBest Life Lyrics[Verse 1]\nBest ...,0.0,2,best life

In [612]:
bed_168 = fetch_lyrics(api, track_name = "No Bullshit", artist_name = "Chris Brown")
bed_240 = fetch_lyrics(api, track_name = "Take Me Away", artist_name = "DJ S.K.T")
bed_455 = fetch_lyrics(api, track_name = "Brighter Days (Marco Lys Remix)", artist_name = "Cajmere")
bed_458 = fetch_lyrics(api, track_name = "Can’t Play Myself (A Tribute To Amy)", artist_name = "Skepta")

Searching for "No Bullshit" by Chris Brown...
Done.

In [618]:
new_bed.loc[168, 'lyrics'] = bed_168
new_bed.loc[240, 'lyrics'] = bed_240
new_bed.loc[455, 'lyrics'] = bed_455
new_bed.loc[458, 'lyrics'] = bed_458

In [619]:
bedroom.loc[234, 'lyrics'] = 'Lyrics not found'

In [624]:
bedroom.loc[new_bed.index, 'lyrics'] = new_bed['lyrics']

In [700]:
bed_6 = fetch_lyrics(api, track_name = "Touch Down", artist_name = "Mella Dee & Storm Mollison")
bed_7 = fetch_lyrics(api, track_name = "Sweet Devotion", artist_name = "TSHA & Caroline Byrne")
bed_64 = fetch_lyrics(api, track_name = "That Sound", artist_name = "Deeper Purpose & GUZ")
bed_139 = fetch_lyrics(api, track_name = "The Take", artist_name = "Tory Lanez")
bed_150 = fetch_lyrics(api, track_name = "It Won’t Stop (Remix)", artist_name = "Sevyn Streeter")
bed_163 = fetch_lyrics(api, track_name = "How You Want It?", artist_name = "Teyana Taylor")
bed_164 = fetch_lyrics(api, track_name = "Earned It", artist_name = "The Weeknd")
bed_231 = fetch_lyrics(api, track_name = "I Went Too Far", artist_name = "AURORA")
bed_246 = fetch_lyrics(api, track_name = "Won't Look Back", artist_name = "Duke Dumont")
bed_252 = fetch_lyrics(api, track_name = "Too Much to Handle (XYconstant Remix)",
                       artist_name = "Great Good Fine OK")
bed_262 = fetch_lyrics(api, track_name = "Feel My Needs", artist_name = "Weiss")
bed_361 = fetch_lyrics(api, track_name = "All My Friends", artist_name = "Snakehips")
bed_530 = fetch_lyrics(api, track_name = "Brighter", artist_name = "Kaskade & Emmit Fenn")
bed_533 = fetch_lyrics(api, track_name = "Time", artist_name = "Carlita (EDM)")
bed_542 = fetch_lyrics(api, track_name = "The Chase", artist_name = "Emmit Fenn")
bed_558 = fetch_lyrics(api, track_name = "It’s Ok It’s Alright", artist_name = "Emmit Fenn")

Searching for "Touch Down" by Mella Dee & Storm Mollison...
Done.

In [717]:
bedroom.loc[6, 'lyrics'] = bed_6
bedroom.loc[7, 'lyrics'] = bed_7
bedroom.loc[139, 'lyrics'] = bed_139
bedroom.loc[150, 'lyrics'] = bed_150
bedroom.loc[163, 'lyrics'] = bed_163
bedroom.loc[164, 'lyrics'] = bed_164
bedroom.loc[231, 'lyrics'] = bed_231
bedroom.loc[246, 'lyrics'] = bed_246
bedroom.loc[252, 'lyrics'] = bed_252
bedroom.loc[262, 'lyrics'] = bed_262
bedroom.loc[361, 'lyrics'] = bed_361
bedroom.loc[530, 'lyrics'] = bed_530
bedroom.loc[533, 'lyrics'] = bed_533
bedroom.loc[542, 'lyrics'] = bed_542
bedroom.loc[558, 'lyrics'] = bed_558

## Mall

In [722]:
mall['track_name_count'] = mall.apply(lambda row: row['lyrics'].lower().count(row['track_name'].lower()), axis=1)
nextt = mall[mall['track_name_count'] == 0][['track_name', 'artist_name', 'lyrics', 'track_name_count']]
nextt=nextt[nextt['lyrics'] != 'Lyrics not found']

nextt = process_lyrics(nextt)

In [723]:
nextt

,track_name,artist_name,lyrics,track_name_count,word_count
2,Dance The Night - From Barbie The Album,Dua Lipa,2 Contributors2024 Nominees LyricsGeneral Fiel...,0,1
14,we can't be friends (wait for your love),Ariana Grande,119 ContributorsTranslationsالعربيةБългарскиDa...,0,3
22,You Make My Heart Go,Sad Puppy,1 ContributorTime Travel LyricsTIME TRAVEL\nSH...,0,0
26,Rush (feat. PinkPantheress & Hyunjin of Stray ...,Troye Sivan,16 ContributorsAugust 2023 Singles Release Cal...,0,3
29,Come On Over,the dreamchild,4 ContributorsThe Year of the Underdogz Lyrics...,0,0
...,...,...,...,...,...
197,Here Comes The Sun - Remastered 2009,The Beatles,3 ContributorsDizaster vs. Soul Khan Lyrics[Ro...,0,0
207,California Dreamin' - Single Version,The Mamas & The Papas,4 ContributorsThe 500 Greatest Songs of All Ti...,0,1
211,Beast Of Burden - Remastered 1994,The Rolling Stones,2 ContributorsRollback LyricsThe elections of ...,0,0
213,Bloom - Bonus Track,The Paper Kites,70 ContributorsSeptember 2023 Album Release Ca...,0,0
237,Dearly Departed (feat. Esmé Patterson),Shakey Graves,1 ContributorDearly departed - live from spoti...,0,1

In [724]:
fetch_lyrics_in_batches(api, nextt)

Searching for "dance the night" by Dua Lipa...
Done.
Searching for "we can't be friends" by Ariana Grande...
Done.
Searching for "you make my heart go" by Sad Puppy...
Done.
Searching for "rush" by Troye Sivan...
Done.
Searching for "come on over" by the dreamchild...
Done.
Searching for "she's not me" by Sad Puppy...
Done.
Searching for "all i want" by Sad Puppy...
Done.
Searching for "rockstars" by Honest Regrets...
Done.
Searching for "die for you" by The Weeknd...
Done.
Searching for "you're not alone" by Sunday Shirt...
Done.
Searching for "i'm good to go" by Balcony Beats...
Done.
Searching for "left right" by Coppermines...
Done.
Searching for "desire" by Calvin Harris...
Done.
Searching for "sweet torture" by Big Z...
Done.
Searching for "alien man" by Sad Puppy...
Done.
Searching for "just friends" by Balcony Beats...
Done.
Searching for "deep down" by Alok...
Done.
Searching for "so easy to love" by Sad Puppy...
Done.
Searching for "good girls" by Balcony Beats...
Done.
Searching for "prayer in c" by Daffix...
Done.
Searching for "west coast high" by Balcony Beats...
Done.
Searching for "want you closer" by Sad Puppy...
Done.
Searching for "mr. right" by DT James...
Done.
Searching for "tattoo" by Eugone...
Done.
Searching for "waking up in rome" by Æj...
Done.
Searching for "21 reasons" by Nathan Dawe...
Done.
Searching for "hello" by Sad Puppy...
Done.
Searching for "i found you" by Cyber Heart...
Done.
Searching for "cold heart" by Elton John...
Done.
Searching for "good on me" by Honey...
Done.
Searching for "no parachute" by Cyber Heart...
Done.
Searching for "sugar crash" by KEES POP...
Done.
Searching for "i had some help" by Post Malone...
Done.
Searching for "mwaki" by Mecdoux...
Done.
Searching for "lost in the night" by Thierry Von Der Warth...
Done.
Searching for "seven nation army" by KHEMIS...
Done.
Searching for "anti-hero" by Taylor Swift...
Done.
Searching for "feel the sunset" by Dawilk...
Done.
Searching for "around the sun" by Thierry Von Der Warth...
Done.
Searching for "texas hold 'em" by Beyoncé...
Done.
Searching for "substitution" by Purple Disco Machine...
Done.
Searching for "back on ibiza" by Vogel...
Done.
Searching for "sunset lovers" by Thierry Von Der Warth...
Done.
Searching for "for life" by Kygo...
Done.
Searching for "lovers in a past life" by Calvin Harris...
Done.
Searching for "i'll be here" by Lane Boy...
Done.
Searching for "would i lie to you" by Thierry Von Der Warth...
Done.
Searching for "you've got the love" by Mahona...
Done.
Searching for "we are the youth" by Solar State...
Done.
Searching for "baby it's summer" by Patrick Lite...
Done.
Searching for "when the rhythm calls" by CARSTN...
Done.
Searching for "yes, and?" by Ariana Grande...
Done.
Searching for "talk about us" by Thierry Von Der Warth...
Done.
Searching for "paradise" by Thierry Von Der Warth...
Done.
Searching for "winner loser" by Blaikz...
Done.
Searching for "long way back to heaven" by DJSM...
Done.
Searching for "paradise" by Thierry Von Der Warth...
Done.
Searching for "catch & release" by LÖVEE...
Done.
Searching for "dreams" by Fleetwood Mac...
Done.
Searching for "here comes the sun" by The Beatles...
Done.
Searching for "california dreamin'" by The Mamas & The Papas...
Done.
Searching for "beast of burden" by The Rolling Stones...
Done.
Searching for "bloom" by The Paper Kites...
Done.
Searching for "dearly departed" by Shakey Graves...
Done.

,track_name,artist_name,lyrics,track_name_count,word_count,cleaned_track_name
2,Dance The Night - From Barbie The Album,Dua Lipa,63 ContributorsTranslationsPortuguêsEspañolFra...,0,1,dance the night
14,we can't be friends (wait for your love),Ariana Grande,119 ContributorsTranslationsالعربيةБългарскиDa...,0,3,we can't be friends
22,You Make My Heart Go,Sad Puppy,1 ContributorTime Travel LyricsTIME TRAVEL\nSH...,0,0,you make my heart go
26,Rush (feat. PinkPantheress & Hyunjin of Stray ...,Troye Sivan,63 ContributorsTranslationsEspañolPortuguêsFra...,0,3,rush
29,Come On Over,the dreamchild,4 ContributorsThe Year of the Underdogz Lyrics...,0,0,come on over
...,...,...,...,...,...,...
197,Here Comes The Sun - Remastered 2009,The Beatles,99 ContributorsTranslationsEspañolPortuguêsHer...,0,0,here comes the sun
207,California Dreamin' - Single Version,The Mamas & The Papas,79 ContributorsTranslationsTürkçeCymraegEspaño...,0,1,california dreamin'
211,Beast Of Burden - Remastered 1994,The Rolling Stones,33 ContributorsBeast of Burden Lyrics[Intro]\n...,0,0,beast of burden
213,Bloom - Bonus Track,The Paper Kites,28 ContributorsBloom Lyrics[Verse 1]\nIn the m...,0,0,bloom
237,Dearly Departed (feat. Esmé Patterson),Shakey Graves,13 ContributorsDearly Departed LyricsOooooh\nO...,0,1,dearly departed

In [793]:
mall.loc[nextt.index, 'lyrics'] = nextt['lyrics']

## Library

In [796]:
library['track_name_count'] = library.apply(lambda row: row['lyrics'].lower().count(row['track_name'].lower()), axis=1)
nextt = library[library['track_name_count'] == 0][['track_name', 'artist_name', 'lyrics', 'track_name_count']]
nextt=nextt[nextt['lyrics'] != 'Lyrics not found']

nextt = process_lyrics(nextt)

In [799]:
library['lyrics'].loc[2]

'Lyrics not found'

In [833]:
lib_126 = fetch_lyrics(api, track_name = "Bailar", artist_name = "Deorro")

Searching for "Bailar" by Deorro...
Done.

In [834]:
lib_137 = fetch_lyrics(api, track_name = "Whatever (Tiësto Remix)", artist_name = "Kygo & Ava Max")

Searching for "Whatever (Tiësto Remix)" by Kygo & Ava Max...
Done.

In [835]:
lib_150 = fetch_lyrics(api, track_name = "Without You", artist_name = "Avicii")

Searching for "Without You" by Avicii...
Done.

In [836]:
lib_151 = fetch_lyrics(api, track_name = "Alors on danse", artist_name = "Stromae")

Searching for "Alors on danse" by Stromae...
Done.

In [837]:
lib_157 = fetch_lyrics(api, track_name = "LET'S GET FKD UP", artist_name = "Alok, Mondello’G & Ceres")

Searching for "LET'S GET FKD UP" by Alok, Mondello’G & Ceres...
Done.

In [838]:
lib_293 = fetch_lyrics(api, track_name = "The Way", artist_name = "Kehlani")

Searching for "The Way" by Kehlani...
Done.

In [839]:
lib_299 = fetch_lyrics(api, track_name = "Ring", artist_name = "Cardi B")

Searching for "Ring" by Cardi B...
Done.

In [840]:
lib_319 = fetch_lyrics(api, track_name = "Love All", artist_name = "Drake")

Searching for "Love All" by Drake...
Done.

In [841]:
lib_322 = fetch_lyrics(api, track_name = "WAIT FOR U", artist_name = "Future")

Searching for "WAIT FOR U" by Future...
Done.

In [842]:
lib_327 = fetch_lyrics(api, track_name = "White Tee", artist_name = "Summer Walker & NO1-NOAH")

Searching for "White Tee" by Summer Walker & NO1-NOAH...
Done.

In [849]:
lib_335 = fetch_lyrics(api, track_name = "Playing Games (Extended Version)", artist_name = "Summer Walker & Bryson Tiller")

Searching for "Playing Games (Extended Version)" by Summer Walker & Bryson Tiller...
Done.

In [845]:
lib_349 = fetch_lyrics(api, track_name = "Drama", artist_name = "Roy Woods")

Searching for "Drama" by Roy Woods...
Done.

In [846]:
lib_352 = fetch_lyrics(api, track_name = "love nwantiti (ah ah ah)", artist_name = "CKay")

Searching for "love nwantiti (ah ah ah)" by CKay...
Done.

In [847]:
lib_360 = fetch_lyrics(api, track_name = "Say My Name", artist_name = "Destiny’s Child")

Searching for "Say My Name" by Destiny’s Child...
Done.

In [848]:
lib_362 = fetch_lyrics(api, track_name = "Girls Need Love (Remix)", artist_name = "Summer Walker & Drake")

Searching for "Girls Need Love (Remix)" by Summer Walker & Drake...
Done.

In [850]:
show_artist_and_track(nextt, 151)

('Stromae', 'Alors on danse - Radio Edit')

In [851]:
nextt.loc[126, 'lyrics'] = lib_126
nextt.loc[137, 'lyrics'] = lib_137
nextt.loc[150, 'lyrics'] = lib_150
nextt.loc[151, 'lyrics'] = lib_151
nextt.loc[157, 'lyrics'] = lib_157
nextt.loc[293, 'lyrics'] = lib_293
nextt.loc[299, 'lyrics'] = lib_299
nextt.loc[319, 'lyrics'] = lib_319
nextt.loc[322, 'lyrics'] = lib_322
nextt.loc[327, 'lyrics'] = lib_327
nextt.loc[335, 'lyrics'] = lib_335
nextt.loc[349, 'lyrics'] = lib_349
nextt.loc[352, 'lyrics'] = lib_352
nextt.loc[360, 'lyrics'] = lib_360
nextt.loc[362, 'lyrics'] = lib_362

In [853]:
library.loc[nextt.index, 'lyrics'] = nextt['lyrics']

## Office

In [855]:
office['track_name_count'] = office.apply(lambda row: row['lyrics'].lower().count(row['track_name'].lower()), axis=1)
nextt = office[office['track_name_count'] == 0][['track_name', 'artist_name', 'lyrics', 'track_name_count']]
nextt=nextt[nextt['lyrics'] != 'Lyrics not found']

nextt = process_lyrics(nextt)

In [857]:
fetch_lyrics_in_batches(api, nextt)

Searching for "house of deer" by VIMES...
Done.
Searching for "millions of time" by Mountains...
Done.
Searching for "west" by Hammock...
Done.
Searching for "stasis" by Solar Bears...
Done.
Searching for "k&f thema" by Apparat...
Done.
Searching for "la femme d'argent" by Air...
Done.
Searching for "down under the manhattan bridge overpass" by Mountains...
Done.
Searching for "stars" by Brian Eno...
Specified song does not contain lyrics. Rejecting.
Searching for "structures from silence" by Steve Roach...
Specified song does not contain lyrics. Rejecting.
Searching for "a feeling of being closer" by Antonymes...
Done.
Searching for "unusual thursday" by Darshan Ambient...
No results found for: 'unusual thursday Darshan Ambient'
Searching for "leaving the tetons" by Mark Preston...
Done.
Searching for "same rules apply" by Clint Mansell...
Done.
Searching for "the mysterious fish named kun" by Aglaia...
Done.
Searching for "the tribe of the flying monkeys" by Aglaia...
Done.
Searching for "seven ancient glaciers" by Aglaia...
Done.
Searching for "hitting the surface" by Monolake...
Done.
Searching for "at les" by Carl Craig...
Done.
Searching for "awash" by Manual...
Done.
Searching for "kissed you by the fountain" by Vector Lovers...
Done.
Searching for "alone on the plateaux" by Simon Lomax...
Done.
Searching for "shelter from the storm" by Rudy Adrian...
Done.
Searching for "absence" by Clark...
Specified song does not contain lyrics. Rejecting.
Searching for "talking book" by Darshan Ambient...
Done.
Searching for "exits" by L. Pierre...
Done.
Searching for "teardrops" by Womack & Womack...
Done.
Searching for "cinema" by Benny Benassi...
Done.
Searching for "one dance" by Drake...
Error fetching lyrics for one dance by Drake: Request timed out:
HTTPSConnectionPool(host='genius.com', port=443): Read timed out. (read timeout=5)
Searching for "hey ya!" by Outkast...
Error fetching lyrics for hey ya! by Outkast: Request timed out:
HTTPSConnectionPool(host='genius.com', port=443): Read timed out. (read timeout=5)
Searching for "ufo" by Sneaky Sound System...
Done.
Searching for "ocean eyes" by Billie Eilish...
Done.
Searching for "brimful of asha" by Cornershop...
Done.
Searching for "get free" by Major Lazer...
Done.
Searching for "easy" by Commodores...
Done.
Searching for "what lovers do" by Maroon 5...
Done.
Searching for "she will be loved" by Maroon 5...
Done.
Searching for "what if i go?" by Mura Masa...
Done.
Searching for "morning after dark" by Timbaland...
Done.
Searching for "leave" by Anne-Marie...
Done.
Searching for "you don't treat me no good" by Chet Faker...
Done.
Searching for "crazy" by Gnarls Barkley...
Done.
Searching for "signed, sealed, delivered" by Stevie Wonder...
Done.
Searching for "higher love" by Steve Winwood...
Done.
Searching for "chateau" by Angus & Julia Stone...
Done.
Searching for "move on up" by Curtis Mayfield...
Done.
Searching for "higher & higher" by Jackie Wilson...
Done.
Searching for "sunflower" by Post Malone...
Done.
Searching for "come and see me" by PARTYNEXTDOOR...
Done.
Searching for "closer" by The Chainsmokers...
Done.
Searching for "airplanes" by B.o.B...
Done.
Searching for "omg" by USHER...
Done.
Searching for "my love" by Justin Timberlake...
Done.
Searching for "what goes around.../...comes around" by Justin Timberlake...
Done.
Searching for "la la land" by Bryce Vine...
Done.
Searching for "we don't talk anymore" by Charlie Puth...
Done.
Searching for "loco contigo" by DJ Snake...
Done.
Searching for "nothing on you" by Ed Sheeran...
Done.
Searching for "stereo hearts" by Gym Class Heroes...
Done.
Searching for "billionaire" by Travie McCoy...
Done.
Searching for "nothin' on you" by B.o.B...
Done.
Searching for "magic" by B.o.B...
Done.
Searching for "obsesion" by Frankie J...
Done.
Searching for "let me hold you" by Bow Wow...
Done.
Searching for "pullin' me back" by Chingy...
Done.
Searching for "hailie's song" by Eminem...
Done.
Searching for "dj got us fallin' in love" by USHER...
Done.
Searching for "give me everything" by Pitbull...
Done.
Searching for "i don't want to be" by Gavin DeGraw...
Done.
Searching for "fendi" by Blaqbonez...
Done.
Searching for "fountains" by Drake...
Done.
Searching for "d o d o" by Tayc...
Done.
Searching for "lazarus" by Dave...
Done.
Searching for "blessed" by Wizkid...
Done.
Searching for "attention" by Omah Lay...
Done.
Searching for "one question" by Zarion Uti...
Done.
Searching for "nature" by Tori Elle...
Done.
Searching for "give up" by Twitch 4EVA...
Done.
Searching for "sugarcane" by Camidoh...
Done.
Searching for "fine wine" by R2Bees...
Done.
Searching for "meliza" by DJ Flex...
Done.
Searching for "summer yomuthi" by Blaq Diamond...
Done.
Searching for "sad girlz luv money remix" by Amaarae...
Done.
Searching for "ke star" by Focalistic...
Done.
Searching for "repeat" by J Hus...
Done.
Searching for "all of this" by Jorja Smith...
Done.
Searching for "colours" by Kid AlpHa...
Done.
Searching for "bad n rude" by King Promise...
Done.
Searching for "monica" by Larry Gaaga...
Done.
Searching for "sungba" by Asake...
Done.
Searching for "fashion killer" by Ayra Starr...
Done.
Searching for "colours" by Kid AlpHa...
Done.
Searching for "stay" by melvitto...
Done.
Searching for "sere" by SPINALL...
Done.
Searching for "loyal" by Tion Wayne...
Done.
Searching for "nyege lewa" by BackRoad Gee...
Done.
Searching for "viva la vida" by Coldplay...
Done.
Searching for "havana" by Camila Cabello...
Done.
Searching for "titanium" by David Guetta...
Done.
Searching for "talk" by Khalid...
Done.
Searching for "get lucky" by Daft Punk...
Done.
Searching for "despacito" by Luis Fonsi...
Done.
Searching for "i knew you were trouble." by Taylor Swift...
Done.
Searching for "dancing with a stranger" by Sam Smith...
Done.
Searching for "my love" by Majid Jordan...
Done.
Searching for "without you" by David Guetta...
Done.
Searching for "feel so close" by Calvin Harris...
Done.
Searching for "just give me a reason" by P!nk...
Done.
Searching for "is it over now?" by Taylor Swift...
Done.
Searching for "stuck with u" by Ariana Grande...
Done.
Searching for "the hardest part" by Olivia Dean...
Done.
Searching for "take my breath" by The Weeknd...
Done.
Searching for "here’s your perfect" by Jamie Miller...
Done.
Searching for "peru" by Fireboy DML...
Done.
Searching for "the rose song" by Olivia Rodrigo...
Done.
Searching for "be who you are" by Jon Batiste...
Done.
Searching for "some things i'll never know" by Teddy Swims...
Done.
Searching for "when was it over?" by Sasha Alex Sloan...
Done.
Searching for "missin' you crazy" by Jon Pardi...
Done.
Searching for "deeper than the holler" by Randy Travis...
Done.
Searching for "'87 chevy 4x4" by Zane Williams...
Done.
Searching for "just wanna rock n roll" by Rodney Atkins...
Done.
Searching for "july in cheyenne" by Aaron Watson...
Done.
Searching for "slow dancing' with a memory" by Darryl Worley...
Done.
Searching for "i'm little but i'm loud" by Kirsty Lee Akers...
Done.
Searching for "my best friend's a girl" by Levi Riggs...
Done.
Searching for "why wait for summer" by Walker Hayes...
Done.
Searching for "tangle me in you" by Roger Creager...
Done.
Searching for "small town usa" by Nathan Dean...
Done.
Searching for "i'm a keeper" by The Band Perry...
Done.
Searching for "spinning my wheels" by Ricky Young...
Done.
Searching for "we can't be friends" by Ariana Grande...
Done.
Searching for "i want to know what love is" by Foreigner...
Done.
Searching for "another day in paradise" by Phil Collins...
Done.
Searching for "i can see clearly now" by Johnny Nash...
Done.
Searching for "symphony" by Clean Bandit...
Done.
Searching for "girls like you" by Maroon 5...
Done.
Searching for "back to you" by Selena Gomez...
Done.
Searching for "footloose" by Kenny Loggins...
Done.
Searching for "true colors" by Cyndi Lauper...
Done.
Searching for "holding back the years" by Simply Red...
Done.
Searching for "it's my life" by Talk Talk...
Done.
Searching for "before you go" by Lewis Capaldi...
Done.
Searching for "perfect duet" by Ed Sheeran...
Done.
Searching for "true" by Spandau Ballet...
Done.
Searching for "wonderful world" by Sam Cooke...
Done.
Searching for "i don't feel like dancin'" by Scissor Sisters...
Done.
Searching for "smooth operator" by Sade...
Done.

,track_name,artist_name,lyrics,track_name_count,word_count,cleaned_track_name
0,House of Deer,VIMES,11 ContributorsFinnegan’s Wake (Chap. 2.3) Lyr...,0,0,house of deer
1,Millions of Time,Mountains,7 ContributorsCircus of Heaven Lyrics[Verse 1]...,0,0,millions of time
7,West,Hammock,3 ContributorsMoby-Dick (Chap. 126: The Life-B...,0,0,west
11,Stasis,Solar Bears,1 ContributorI Played Everything LyricsI’ve pl...,0,0,stasis
16,K&F Thema,Apparat,2 ContributorsZelda LyricsCutting right up whe...,0,0,k&f thema
...,...,...,...,...,...,...
700,Perfect Duet (Ed Sheeran & Beyoncé),Ed Sheeran,81 ContributorsPerfect Duet Lyrics[Verse 1: Ed...,0,1,perfect duet
701,True - Single Edit,Spandau Ballet,50 ContributorsTrue Lyrics[Intro]\nHuh huh uh-...,0,1,true
722,(What A) Wonderful World,Sam Cooke,30 ContributorsTranslationsDeutschWonderful Wo...,0,3,wonderful world
727,I Don't Feel Like Dancin' - Radio Edit,Scissor Sisters,29 ContributorsI Don’t Feel Like Dancin’ Lyric...,0,6,i don't feel like dancin'
729,Smooth Operator - 2011 Remastered,Sade,83 ContributorsTranslationsDeutschSmooth Opera...,0,0,smooth operator

In [906]:
off_100 = fetch_lyrics(api, track_name = "One Dance", artist_name = "Drake")
off_109 = fetch_lyrics(api, track_name = "Hey Ya!", artist_name = "OutKast")
off_203 = fetch_lyrics(api, track_name = "What Goes Around... Comes Around (Interlude)", artist_name = "Justin Timberlake")
off_335 = fetch_lyrics(api, track_name = "Fashion Killa", artist_name = "Ayra Starr")

Searching for "One Dance" by Drake...
Done.

In [915]:
nextt.loc[100, 'lyrics'] = off_100
nextt.loc[109, 'lyrics'] = off_109
nextt.loc[203, 'lyrics'] = off_203
nextt.loc[335, 'lyrics'] = off_335

In [917]:
office.loc[nextt.index, 'lyrics'] = nextt['lyrics']

## Restaurant

In [919]:
restaurant['track_name_count'] = restaurant.apply(lambda row: row['lyrics'].lower().count(row['track_name'].lower()), axis=1)
nextt = restaurant[restaurant['track_name_count'] == 0][['track_name', 'artist_name', 'lyrics', 'track_name_count']]
nextt=nextt[nextt['lyrics'] != 'Lyrics not found']

nextt = process_lyrics(nextt)

In [921]:
fetch_lyrics_in_batches(api, nextt)

Searching for "lovely day" by Bill Withers...
Done.
Searching for "lavender haze" by Taylor Swift...
Done.
Searching for "some things i'll never know" by Teddy Swims...
Done.
Searching for "watermelon sugar" by Emei...
Done.
Searching for "lift me up" by Rihanna...
Done.
Searching for "july" by Noah Cyrus...
Done.
Searching for "this must be the place" by Talking Heads...
Done.
Searching for "one of these nights" by Eagles...
Done.
Searching for "and i love her" by The Beatles...
Done.
Searching for "what you won't do for love" by Bobby Caldwell...
Done.
Searching for "a thousand miles" by Vanessa Carlton...
Done.
Searching for "bloom" by The Paper Kites...
Done.
Searching for "always on my mind" by Nané...
Done.
Searching for "sun & moon" by BALTHVS...
Done.
Searching for "nantucket island" by Willie Wright...
Done.
Searching for "mambo sun" by T. Rex...
Done.
Searching for "people never change" by Peter Cat Recording Co....
Done.
Searching for "feed the fire" by SG Lewis...
Done.
Searching for "take what's given" by BADBADNOTGOOD...
Done.
Searching for "dark days [feat. sylvan esso]" by Local Natives...
Done.
Searching for "girlfriend is better" by Talking Heads...
Done.
Searching for "let 'em in" by Wings...
Done.
Searching for "thank you" by Bonnie Raitt...
Done.
Searching for "don't you evah" by Spoon...
Done.
Searching for "more than a woman" by Bee Gees...
Done.
Searching for "run your mouth" by The Mar√≠as...
Done.
Searching for "charmed" by Œ£tella...
No results found for: 'charmed Œ£tella'
Searching for "i, nietzsche" by Fenne Lily...
Done.
Searching for "eye to eye" by John Smith...
Done.
Searching for "london's song" by Matt Hartke...
Done.
Searching for "bright star" by Ana√Øs Mitchell...
Done.
Searching for "nothing arrived" by Villagers...
Done.
Searching for "sweet misery" by Tr√© Burt...
Done.
Searching for "driving alone in the city at night" by Joshua Burnside...
Done.
Searching for "thousand" by Rosie Carney...
Done.
Searching for "something in the orange" by Zach Bryan...
Done.
Searching for "it's called: freefall" by Paris Paloma...
Done.
Searching for "all is well" by Avi Kaplan...
Done.
Searching for "you and i" by Valerie June...
Done.
Searching for "for all you give" by The Paper Kites...
Done.
Searching for "nothing's gonna happen" by The Staves...
Done.
Searching for "scared to start" by Michael Marcagi...
Done.
Searching for "someday i'll get it" by Alek Olsen...
Done.
Searching for "cherry wine" by Hozier...
Done.
Searching for "a new romance" by Alexandra Streliski...
Done.
Searching for "through the blue" by Roger Eno...
Specified song does not contain lyrics. Rejecting.
Searching for "consolations, s. 172: no. 3, lento placido" by Franz Liszt...
Done.
Searching for "sheep may safely graze" by Alexis Ffrench...
Done.
Searching for "hall of fame" by The Script...
Done.
Searching for "bohemian rhapsody" by Queen...
Done.
Searching for "what's love got to do with it" by Tina Turner...
Done.
Searching for "too good at goodbyes" by Sam Smith...
Done.
Searching for "she will be loved" by Maroon 5...
Done.
Searching for "free fallin'" by John Mayer...
Done.
Searching for "rude" by MAGIC!...
Done.
Searching for "love is all around" by Wet Wet Wet...
Done.
Searching for "message in a bottle" by The Police...
Done.
Searching for "sweet home alabama" by Lynyrd Skynyrd...
Done.
Searching for "the cave" by Mumford & Sons...
Done.
Searching for "i don't want to be" by Gavin DeGraw...
Done.
Searching for "harder to breathe" by Maroon 5...
Done.
Searching for "shape of you" by Ed Sheeran...
Error fetching lyrics for shape of you by Ed Sheeran: Request timed out:
HTTPSConnectionPool(host='genius.com', port=443): Read timed out. (read timeout=5)
Searching for "i will wait" by Mumford & Sons...
Done.
Searching for "bless the broken road" by Rascal Flatts...
Done.
Searching for "somebody like you" by Keith Urban...
Done.
Searching for "even if it breaks your heart" by Eli Young Band...
Done.
Searching for "these foolish things" by Rod Stewart...
Done.
Searching for "walking away" by Craig David...
Done.
Searching for "fix you" by Coldplay...
Done.
Searching for "bonfire heart" by James Blunt...
Done.
Searching for "american pie" by Don McLean...
Done.
Searching for "let her go" by Passenger...
Done.
Searching for "take me to church" by Hozier...
Done.
Searching for "right here waiting for you" by Passion Beat...
Done.
Searching for "our house" by Madness...
Done.
Searching for "don't let the sun go down on me" by Elton John...
Done.
Searching for "chasing pavements" by Adele...
Done.
Searching for "something just like this" by The Chainsmokers...
Done.
Searching for "way down we go" by KALEO...
Done.
Searching for "viva la vida" by slowli...
Done.
Searching for "shameless" by slowli...
Specified song does not contain lyrics. Rejecting.
Searching for "apologize" by slowli...
Done.
Searching for "rush" by slowli...
Done.
Searching for "the night we met" by slowli...
Done.
Searching for "closer" by slowli...
Specified song does not contain lyrics. Rejecting.
Searching for "young and beautiful" by slowli...
Done.
Searching for "yes to heaven" by slowli...
Done.
Searching for "sweater weather" by 90degrees...
Done.
Searching for "supergirl" by Way 2 Fast...
Done.
Searching for "numb" by Way 2 Fast...
Done.
Searching for "te amo" by Way 2 Fast...
Done.
Searching for "everytime we touch" by Way 2 Fast...
Done.
Searching for "end of the world" by Way 2 Fast...
Done.
Searching for "big on tiktok" by Way 2 Fast...
Done.
Searching for "i'm good" by Way 2 Fast...
Done.
Searching for "cupid's chokehold / breakfast in america" by Way 2 Fast...
No results found for: 'cupid's chokehold / breakfast in america Way 2 Fast'
Searching for "lift me up" by Way 2 Fast...
Done.
Searching for "dancing on my own" by Way 2 Fast...
Done.
Searching for "summer sound" by FRNDLY...
Done.
Searching for "smack that" by Way 2 Fast...
Done.
Searching for "as it was" by Way 2 Fast...
Done.
Searching for "space song" by Way 2 Fast...
Done.
Searching for "don't let me down" by Way 2 Fast...
Done.
Searching for "teenage dirtbag" by Cherry Girl...
Done.
Searching for "mary on a cross" by Way 2 Fast...
Done.
Searching for "say it right" by iykyk...
Done.
Searching for "children" by Way 2 Fast...
Done.
Searching for "all the same" by dxncing dxvil...
Done.
Searching for "titanium" by Way 2 Fast...
Done.
Searching for "disturbia" by Hiko...
Done.
Searching for "crazy" by Way 2 Fast...
Done.
Searching for "better with you" by chxos...
Done.
Searching for "big jet plane" by Way 2 Fast...
Done.
Searching for "flowers" by Way 2 Fast...
Done.
Searching for "apologize" by Way 2 Fast...
Done.
Searching for "shameless" by Way 2 Fast...
Done.
Searching for "shameless" by Way 2 Hard...
Done.
Searching for "getting older" by dxncing dxvil...
Done.
Searching for "new age" by Way 2 Fast...
Done.
Searching for "big jet plane" by Way 2 Hard...
Done.
Searching for "the night we met" by Way 2 Fast...
Done.
Searching for "all of me" by Way 2 Fast...
Done.
Searching for "closer" by Way 2 Fast...
Done.
Searching for "lost" by Way 2 Fast...
Done.
Searching for "play hard" by Way 2 Fast...
Done.
Searching for "where have you been" by Way 2 Fast...
Done.
Searching for "unfaithful" by Way 2 Fast...
Done.
Searching for "young and beautiful" by Way 2 Fast...
Done.
Searching for "rush" by Way 2 Fast...
Done.
Searching for "yes to heaven" by Way 2 Hard...
Done.
Searching for "tik tok" by Way 2 Fast...
Done.
Searching for "boy‚äôs a liar pt. 2" by Way 2 Fast...
Done.
Searching for "only for one night" by dxncing dxvil...
Done.
Searching for "lose you to love me" by Way 2 Fast...
Done.
Searching for "dancing with your ghost" by Way 2 Fast...
Done.
Searching for "the grants" by Way 2 Fast...
Done.
Searching for "hot n cold" by Syrex...
Done.
Searching for "all of the girls you loved before" by Way 2 Fast...
Done.
Searching for "te amo" by Way 2 Hard...
Done.
Searching for "just dance" by Muppet DJ...
Done.
Searching for "give it to me" by Way 2 Fast...
Done.
Searching for "creepin'" by Way 2 Fast...
Done.
Searching for "ceilings" by pearl...
Done.
Searching for "yes to heaven" by Way 2 Fast...
Done.
Searching for "te amo" by Way 2 Fast...
Done.
Searching for "trance" by Xanemusic...
No results found for: 'trance Xanemusic'
Searching for "kill bill" by Way 2 Fast...
Done.
Searching for "bloody mary" by Way 2 Fast...
Done.
Searching for "it's called: freefall" by noturgf...
No results found for: 'it's called: freefall noturgf'
Searching for "viva la vida" by Way 2 Fast...
Done.
Searching for "if we ever broke up" by Way 2 Fast...
Done.
Searching for "pretty girls walk" by Way 2 Fast...
Done.
Searching for "mad love" by Mabel...
Done.
Searching for "cupid twin ver." by Way 2 Fast...
Done.
Searching for "whenever, wherever" by Way 2 Fast...
Done.
Searching for "die for you" by The Weeknd...
Done.
Searching for "hundred miles" by Way 2 Fast...
Done.
Searching for "radio" by Way 2 Fast...
Done.
Searching for "love on the radio" by Matthew West...
Done.
Searching for "smoke and mirrors" by The Belonging Co...
Done.
Searching for "the a team" by Ed Sheeran...
Done.
Searching for "someone like you" by Adele...
Done.
Searching for "if i ain't got you" by Alicia Keys...
Done.
Searching for "piano man" by Billy Joel...
Done.
Searching for "7 years" by Lukas Graham...
Done.
Searching for "ordinary people" by John Legend...
Done.
Searching for "catch & release" by Matt Simons...
Done.
Searching for "i see fire" by Ed Sheeran...
Done.
Searching for "warwick avenue" by Duffy...
Done.
Searching for "come away with me" by Norah Jones...
Done.
Searching for "i'm yours" by Jason Mraz...
Done.
Searching for "chan chan" by Buena Vista Social Club...
Done.
Searching for "better together" by Jack Johnson...
Done.
Searching for "make you feel my love" by Adele...
Done.
Searching for "love yourself" by Justin Bieber...
Done.
Searching for "the dock of the bay" by Otis Redding...
Done.
Searching for "don't know why" by Norah Jones...
Done.
Searching for "stay with me" by Sam Smith...
Done.
Searching for "all of me" by John Legend...
Done.
Searching for "thinking out loud" by Ed Sheeran...
Done.
Searching for "crowded table" by The Highwomen...
Done.
Searching for "the joke" by Brandi Carlile...
Done.
Searching for "late night feelings" by Mark Ronson...
Done.
Searching for "falling into place" by Victor Ray...
Done.
Searching for "stronger" by Thunderstorm Artis...
Done.
Searching for "love like this" by Kodaline...
Done.
Searching for "fields of gold" by Sting...
Done.
Searching for "that's what i like" by Bruno Mars...
Done.
Searching for "ms. jackson" by Outkast...
Done.
Searching for "lovely day" by Bill Withers...
Done.
Searching for "happy" by Pharrell Williams...
Done.
Searching for "cuff it" by Beyoncé...
Done.
Searching for "family affair" by Mary J. Blige...
Done.
Searching for "boogie wonderland" by Earth, Wind & Fire...
Done.
Searching for "doo wop" by Ms. Lauryn Hill...
Done.
Searching for "let's stay together" by Al Green...
Done.
Searching for "return of the mack" by Mark Morrison...
Done.
Searching for "crank that" by Soulja Boy...
Done.
Searching for "don't stop 'til you get enough" by Michael Jackson...
Error fetching lyrics for don't stop 'til you get enough by Michael Jackson: Request timed out:
HTTPSConnectionPool(host='genius.com', port=443): Read timed out. (read timeout=5)
Searching for "never too much" by Luther Vandross...
Done.
Searching for "let's groove" by Earth, Wind & Fire...
Done.
Searching for "love on top" by Beyoncé...
Done.
Searching for "remember the time" by Michael Jackson...
Done.
Searching for "super freak" by Rick James...
Done.
Searching for "the way you move" by Outkast...
Done.
Searching for "can't get enough of your love, babe" by Barry White...
Done.
Searching for "p.y.t." by Michael Jackson...
Done.
Searching for "this is how we do it" by Montell Jordan...
Done.
Searching for "when doves cry" by Prince...
Done.
Searching for "got to be real" by Cheryl Lynn...
Done.
Searching for "ain't nobody" by Rufus...
Done.
Searching for "love like this" by Faith Evans...
Done.
Searching for "brick house" by Commodores...
Done.
Searching for "oh honey" by Delegation...
Done.
Searching for "back to life" by Soul II Soul...
Done.
Searching for "give it to me baby" by Rick James...
Done.
Searching for "i wanna be down" by Brandy...
Done.
Searching for "can we talk" by Tevin Campbell...
Done.
Searching for "i'll take you there" by The Staple Singers...
Done.
Searching for "int'l players anthem" by UGK...
Done.
Searching for "hey mr. d.j." by Zhané...
Done.
Searching for "my boo" by Ghost Town DJs...
Done.
Searching for "word up" by Cameo...
Done.
Searching for "one more chance / stay with me" by The Notorious B.I.G....
Done.
Searching for "cupid shuffle" by Cupid...
Done.
Searching for "ascension" by Maxwell...
Done.
Searching for "right here" by SWV...
Done.
Searching for "could you be loved" by Bob Marley & The Wailers...
Done.
Searching for "footsteps in the dark, pts. 1 & 2" by The Isley Brothers...
Done.
Searching for "cruisin'" by Smokey Robinson...
Done.
Searching for "i feel for you" by Chaka Khan...
Done.
Searching for "just fine" by Mary J. Blige...
Done.
Searching for "if it isn't love" by New Edition...
Done.
Searching for "party" by Beyoncé...
Done.
Searching for "still not a player" by Big Pun...
Done.
Searching for "between the sheets" by The Isley Brothers...
Done.
Searching for "summer madness" by Kool & The Gang...
Specified song does not contain lyrics. Rejecting.
Searching for "do i do" by Stevie Wonder...
Done.
Searching for "workin' day and night" by Michael Jackson...
Done.
Searching for "just friends" by Musiq Soulchild...
Done.
Searching for "remind me" by Patrice Rushen...
Done.
Searching for "sweet thing" by Rufus...
Done.
Searching for "flash light" by Parliament...
Done.
Searching for "why don't we fall in love" by Amerie...
Done.
Searching for "fantasy" by Mariah Carey...
Done.
Searching for "people everyday" by Arrested Development...
Done.
Searching for "thank you" by Sly & The Family Stone...
Done.
Searching for "feels good" by Tony! Toni! Toné!...
Done.
Searching for "before i let go" by Beyoncé...
Done.
Searching for "all night long" by Mary Jane Girls...
Error fetching lyrics for all night long by Mary Jane Girls: Request timed out:
HTTPSConnectionPool(host='genius.com', port=443): Read timed out. (read timeout=5)

,track_name,artist_name,lyrics,track_name_count,word_count,cleaned_track_name
0,Lovely Day - Studio Rio Version,Bill Withers,46 ContributorsLovely Day Lyrics[Verse 1]\nWhe...,0,0,lovely day
4,Lavender Haze - Acoustic Version,Taylor Swift,126 ContributorsTranslationsEspañolFrançaisPor...,0,7,lavender haze
6,Some Things I'll Never Know (feat. Maren Morris),Teddy Swims,5 ContributorsTranslationsУкраїнськаSome Thing...,0,0,some things i'll never know
12,Watermelon Sugar - Spotify Singles,Emei,4 ContributorsWatermelon Sugar (Spotify Single...,0,22,watermelon sugar
36,Lift Me Up - From Black Panther: Wakanda Forev...,Rihanna,109 ContributorsTranslationsPortuguêsTürkçeEsp...,0,1,lift me up
...,...,...,...,...,...,...
575,People Everyday - Metamorphosis Mix,Arrested Development,1 ContributorPeople Everyday (unplugged) Lyric...,0,0,people everyday
576,Thank You (Falettinme Be Mice Elf Agin) - Sing...,Sly & The Family Stone,2 ContributorsThanx 4 the Funk Lyrics[Intro]\n...,0,0,thank you
577,Feels Good,Tony! Toni! Toné!,21 ContributorsFeels Good Lyrics[Intro]\nPlay ...,0,0,feels good
578,Before I Let Go - Homecoming Live Bonus Track,Beyoncé,63 ContributorsTranslationsBeyoncé - Before I ...,0,0,before i let go
579,All Night Long,Mary Jane Girls,Error: Request timed out:\nHTTPSConnectionPool...,0,0,all night long

In [1056]:
restaurant.loc[181, 'artist_name'] = "The Marías"
restaurant.loc[207, 'artist_name'] = "Anaïs Mitchell"
restaurant.loc[215, 'artist_name'] = "Tré Burt"
restaurant.loc[443, 'track_name'] = "Boy’s a liar Pt. 2 (Sped Up)"

In [1058]:
rest_518 = fetch_lyrics(api, track_name = "Don't Stop 'Til You Get Enough", artist_name = "Michael Jackson")
rest_537 = fetch_lyrics(api, track_name = "Back to Life (However Do You Want Me)", artist_name = "Soul II Soul")
rest_543 = fetch_lyrics(api, track_name = "Int’l Players Anthem (I Choose You)", artist_name = "UGK")
rest_547 = fetch_lyrics(api, track_name = "One More Chance / Stay With Me (Remix))", artist_name = "The Notorious B.I.G.")
rest_576 = fetch_lyrics(api, track_name = "Thank You (Falettinme Be Mice Elf Agin)", artist_name = "Sly and the Family Stone")
rest_579 = fetch_lyrics(api, track_name = "All Night Long", artist_name = "Mary Jane Girls")
rest_181 = fetch_lyrics(api, track_name = "Run Your Mouth", artist_name = "The Marías")
rest_207 = fetch_lyrics(api, track_name = "Bright Star", artist_name = "Anaïs Mitchell")
rest_215 = fetch_lyrics(api, track_name = "Sweet Misery", artist_name = "Tré Burt")
rest_363 = fetch_lyrics(api, track_name = "Shape of You", artist_name = "Ed Sheeran")
rest_388 = fetch_lyrics(api, track_name = "Viva La Vida", artist_name = "Coldplay")
rest_392 = fetch_lyrics(api, track_name = "The Night We Met (Remix)", artist_name = "Lord Huron")
rest_394 = fetch_lyrics(api, track_name = "Young and Beautiful", artist_name = "Lana Del Rey")
rest_398 = fetch_lyrics(api, track_name = "Numb", artist_name = "Linkin Park")
rest_399 = fetch_lyrics(api, track_name = "Te Amo", artist_name = "Rihanna")
rest_400 = fetch_lyrics(api, track_name = "Everytime We Touch", artist_name = "Cascada")
rest_403 = fetch_lyrics(api, track_name = "I’m Good (Blue)", artist_name = "David Guetta & Bebe Rexha")
rest_404 = fetch_lyrics(api, track_name = "Cupid’s Chokehold / Breakfast in America", artist_name = "Gym Class Heroes")
rest_406 = fetch_lyrics(api, track_name = "Lift Me Up", artist_name = "Rihanna")
rest_407 = fetch_lyrics(api, track_name = "Dancing on My Own", artist_name = "Calum Scott")
rest_409 = fetch_lyrics(api, track_name = "Smack That", artist_name = "Akon")
rest_410 = fetch_lyrics(api, track_name = "As It Was", artist_name = "Harry Styles")
rest_411 = fetch_lyrics(api, track_name = "Space Song (Slowed and Reverb)", artist_name = "Beach House")
rest_412 = fetch_lyrics(api, track_name = "Don’t Let Me Down", artist_name = "The Chainsmokers")
rest_414 = fetch_lyrics(api, track_name = "Mary on a Cross", artist_name = "Ghost")
rest_418 = fetch_lyrics(api, track_name = "Titanium", artist_name = "David Guetta")
rest_419 = fetch_lyrics(api, track_name = "Disturbia", artist_name = "Rihanna")
rest_420 = fetch_lyrics(api, track_name = "Crazy", artist_name = "Gnarls Barkley")
rest_422 = fetch_lyrics(api, track_name = "Big Jet Plane", artist_name = "Angus & Julia Stone")
rest_423 = fetch_lyrics(api, track_name = "Flower", artist_name = "Miley Cyrus")
rest_425 = fetch_lyrics(api, track_name = "Apologize", artist_name = "Timbaland")
rest_426 = fetch_lyrics(api, track_name = "Shameless", artist_name = "Camila Cabello")
rest_430 = fetch_lyrics(api, track_name = "Big Jet Plane", artist_name = "Angus & Julia Stone")
rest_431 = fetch_lyrics(api, track_name = "The Night We Met (Remix)", artist_name = "Lord Huron")
rest_432 = fetch_lyrics(api, track_name = "All of Me", artist_name = "John Legend")
rest_433 = fetch_lyrics(api, track_name = "Closer", artist_name = "The Chainsmokers")
rest_434 = fetch_lyrics(api, track_name = "Lost", artist_name = "Linkin Park")
rest_436 = fetch_lyrics(api, track_name = "Play Hard", artist_name = "David Guetta")
rest_437 = fetch_lyrics(api, track_name = "Where Have You Been", artist_name = "Rihanna")
rest_438 = fetch_lyrics(api, track_name = "Unfaithful", artist_name = "Rihanna")
rest_439 = fetch_lyrics(api, track_name = "Young and Beautiful", artist_name = "Lana Del Rey")
rest_440 = fetch_lyrics(api, track_name = "Rush", artist_name = "Ayra Starr")
rest_441 = fetch_lyrics(api, track_name = "Say Yes To Heaven", artist_name = "Lana Del Rey")
rest_443 = fetch_lyrics(api, track_name = "Boy’s a liar Pt. 2", artist_name = "PinkPantheress & Ice Spice")
rest_445 = fetch_lyrics(api, track_name = "Lose You To Love Me", artist_name = "Selena Gomez")
rest_446 = fetch_lyrics(api, track_name = "Dancing With Your Ghost", artist_name = "Sasha Alex Sloan")
rest_447 = fetch_lyrics(api, track_name = "The Grants", artist_name = "Lana Del Rey")
rest_448 = fetch_lyrics(api, track_name = "Hot N Cold", artist_name = "Katy Perry")
rest_449 = fetch_lyrics(api, track_name = "All Of The Girls You Loved Before", artist_name = "Taylor Swift")
rest_450 = fetch_lyrics(api, track_name = "Te Amo", artist_name = "Rihanna")
rest_451 = fetch_lyrics(api, track_name = "Just Dance", artist_name = "Lady Gaga")
rest_452 = fetch_lyrics(api, track_name = "Give It To Me", artist_name = "Timbaland")
rest_453 = fetch_lyrics(api, track_name = "Creepin'", artist_name = "Metro Boomin, The Weeknd & 21 Savage")
rest_454 = fetch_lyrics(api, track_name = "ceilings", artist_name = "Lizzy McAlpine")
rest_455 = fetch_lyrics(api, track_name = "Say Yes To Heaven", artist_name = "Lana Del Rey")
rest_456 = fetch_lyrics(api, track_name = "Te Amo", artist_name = "Rihanna")
rest_457 = fetch_lyrics(api, track_name = "Trance", artist_name = "Metro Boomin, Travis Scott & Young Thug")
rest_458 = fetch_lyrics(api, track_name = "Kill Bill", artist_name = "SZA")
rest_459 = fetch_lyrics(api, track_name = "Bloody Mary", artist_name = "Lady Gaga")
rest_460 = fetch_lyrics(api, track_name = "It's Called: Freefall", artist_name = "Rainbow Kitten Surprise")
rest_461 = fetch_lyrics(api, track_name = "Viva La Vida", artist_name = "Coldplay")
rest_462 = fetch_lyrics(api, track_name = "If We Ever Broke Up", artist_name = "Mae Stephens")
rest_463 = fetch_lyrics(api, track_name = "Pretty Girls Walk", artist_name = "Big Boss Vette")
rest_464 = fetch_lyrics(api, track_name = "Mad Love", artist_name = "Mabel")
rest_465 = fetch_lyrics(api, track_name = "Cupid (Twin Version)", artist_name = "FIFTY FIFTY (피프티피프티)")
rest_466 = fetch_lyrics(api, track_name = "Whenever, Wherever", artist_name = "Shakira")
rest_467 = fetch_lyrics(api, track_name = "Die For You", artist_name = "The Weeknd")
rest_468 = fetch_lyrics(api, track_name = "Hundred Miles (Extended Mix)", artist_name = "Yall & Gabriela Richardson")
rest_469 = fetch_lyrics(api, track_name = "Radio", artist_name = "Lana Del Rey")

Searching for "Don't Stop 'Til You Get Enough" by Michael Jackson...
Done.

In [1134]:
show_artist_and_track(nextt, 404)

('Way 2 Fast', "Cupid's Chokehold / Breakfast in America - sped up")

In [1135]:
nextt.loc[469, 'lyrics'] = rest_469
nextt.loc[468, 'lyrics'] = rest_468
nextt.loc[467, 'lyrics'] = rest_467
nextt.loc[466, 'lyrics'] = rest_466
nextt.loc[465, 'lyrics'] = rest_465
nextt.loc[464, 'lyrics'] = rest_464
nextt.loc[463, 'lyrics'] = rest_463
nextt.loc[462, 'lyrics'] = rest_462
nextt.loc[461, 'lyrics'] = rest_461
nextt.loc[460, 'lyrics'] = rest_460
nextt.loc[459, 'lyrics'] = rest_459
nextt.loc[458, 'lyrics'] = rest_458
nextt.loc[457, 'lyrics'] = rest_457
nextt.loc[456, 'lyrics'] = rest_456
nextt.loc[455, 'lyrics'] = rest_455
nextt.loc[454, 'lyrics'] = rest_454
nextt.loc[453, 'lyrics'] = rest_453
nextt.loc[452, 'lyrics'] = rest_452
nextt.loc[451, 'lyrics'] = rest_451
nextt.loc[450, 'lyrics'] = rest_450
nextt.loc[449, 'lyrics'] = rest_449
nextt.loc[448, 'lyrics'] = rest_448
nextt.loc[447, 'lyrics'] = rest_447
nextt.loc[446, 'lyrics'] = rest_446
nextt.loc[445, 'lyrics'] = rest_445
nextt.loc[443, 'lyrics'] = rest_443
nextt.loc[441, 'lyrics'] = rest_441
nextt.loc[440, 'lyrics'] = rest_440
nextt.loc[439, 'lyrics'] = rest_439
nextt.loc[438, 'lyrics'] = rest_438
nextt.loc[437, 'lyrics'] = rest_437
nextt.loc[436, 'lyrics'] = rest_436
nextt.loc[434, 'lyrics'] = rest_434
nextt.loc[433, 'lyrics'] = rest_433
nextt.loc[432, 'lyrics'] = rest_432
nextt.loc[431, 'lyrics'] = rest_431
nextt.loc[430, 'lyrics'] = rest_430
nextt.loc[426, 'lyrics'] = rest_426
nextt.loc[425, 'lyrics'] = rest_425
nextt.loc[423, 'lyrics'] = rest_423
nextt.loc[422, 'lyrics'] = rest_422
nextt.loc[420, 'lyrics'] = rest_420
nextt.loc[419, 'lyrics'] = rest_419
nextt.loc[418, 'lyrics'] = rest_418
nextt.loc[414, 'lyrics'] = rest_414
nextt.loc[412, 'lyrics'] = rest_412
nextt.loc[411, 'lyrics'] = rest_411
nextt.loc[410, 'lyrics'] = rest_410
nextt.loc[409, 'lyrics'] = rest_409
nextt.loc[407, 'lyrics'] = rest_407
nextt.loc[406, 'lyrics'] = rest_406
nextt.loc[404, 'lyrics'] = rest_404
nextt.loc[403, 'lyrics'] = rest_403
nextt.loc[400, 'lyrics'] = rest_400
nextt.loc[399, 'lyrics'] = rest_399
nextt.loc[398, 'lyrics'] = rest_398
nextt.loc[394, 'lyrics'] = rest_394
nextt.loc[392, 'lyrics'] = rest_392
nextt.loc[388, 'lyrics'] = rest_388
nextt.loc[363, 'lyrics'] = rest_363
nextt.loc[215, 'lyrics'] = rest_215
nextt.loc[207, 'lyrics'] = rest_207
nextt.loc[181, 'lyrics'] = rest_181
nextt.loc[579, 'lyrics'] = rest_579
nextt.loc[576, 'lyrics'] = rest_576
nextt.loc[547, 'lyrics'] = rest_547
nextt.loc[543, 'lyrics'] = rest_543
nextt.loc[537, 'lyrics'] = rest_537
nextt.loc[518, 'lyrics'] = rest_518

In [1136]:
restaurant.loc[nextt.index, 'lyrics'] = nextt['lyrics']

## TrainBus

In [1143]:
trainBus['track_name_count'] = trainBus.apply(lambda row: row['lyrics'].lower().count(row['track_name'].lower()), axis=1)
nextt = trainBus[trainBus['track_name_count'] == 0][['track_name', 'artist_name', 'lyrics', 'track_name_count']]
nextt=nextt[nextt['lyrics'] != 'Lyrics not found']

nextt = process_lyrics(nextt)

In [1145]:
fetch_lyrics_in_batches(api, nextt)

Searching for "no scrubs" by TLC...
Done.
Searching for "hypnotize" by The Notorious B.I.G....
Done.
Searching for "what's luv?" by Fat Joe...
Done.
Searching for "crazy in love" by Beyoncé...
Done.
Searching for "jenny from the block" by Jennifer Lopez...
Done.
Searching for "yeah!" by USHER...
Done.
Searching for "99 problems" by JAY-Z...
Error fetching lyrics for 99 problems by JAY-Z: Request timed out:
HTTPSConnectionPool(host='genius.com', port=443): Read timed out. (read timeout=5)
Searching for "la tortura" by Shakira...
Done.
Searching for "my name is" by Eminem...
Error fetching lyrics for my name is by Eminem: Request timed out:
HTTPSConnectionPool(host='genius.com', port=443): Read timed out. (read timeout=5)
Searching for "independent women, pt. 1" by Destiny's Child...
Done.
Searching for "shake ya ass" by Mystikal...
Done.
Searching for "bump n' grind" by R. Kelly...
Done.
Searching for "keep on, keepin' on" by MC Lyte...
Done.
Searching for "low" by Flo Rida...
Done.
Searching for "the safety dance" by Men Without Hats...
Done.
Searching for "girls, girls, girls" by JAY-Z...
Done.
Searching for "rock your body" by Justin Timberlake...
Done.
Searching for "i kissed a girl" by Katy Perry...
Done.
Searching for "you make me wanna..." by USHER...
Done.
Searching for "work it" by Missy Elliott...
Done.
Searching for "my love is like...wo" by Mýa...
Done.
Searching for "cut!" by Maren Morris...
Done.
Searching for "give you the world" by Marc Broussard...
Done.
Searching for "high road" by Koe Wetzel...
Done.
Searching for "scared to start" by Michael Marcagi...
Done.
Searching for "friend like you" by Tyrone Wells...
Done.
Searching for "some things i'll never know" by Teddy Swims...
Done.
Searching for "little blue" by Jacob Collier...
Done.
Searching for "life lesson" by Jon Batiste...
Done.
Searching for "i'm here" by Matteo Bocelli...
Done.
Searching for "lifeline" by Alicia Keys...
Done.
Searching for "the sound of silence" by Amira Unplugged...
Done.
Searching for "when i get there" by P!nk...
Done.
Searching for "loved" by Leslie Odom Jr....
Done.
Searching for "don't make sense" by Shannon Lauren Callihan...
Done.
Searching for "leave it better than you found it" by Judah & the Lion...
Done.
Searching for "if you love me" by Michael Schulte...
Done.
Searching for "antidote" by Guy Sebastian...
Done.
Searching for "i don't wanna dance" by Charlotte Lawrence...
Done.
Searching for "i don’t wanna see you try" by Sam MacPherson...
Done.
Searching for "i guess" by Lizzy McAlpine...
Done.
Searching for "one last dance" by Baby Rose...
Done.
Searching for "redbull" by Leyla Blue...
Done.
Searching for "black car" by Joy Oladokun...
Done.
Searching for "somebody" by TSHA...
Done.
Searching for "i get it now" by Hunter Hayes...
Done.
Searching for "sad forever" by Lauren Spencer Smith...
Done.
Searching for "dream boy" by Stacey Ryan...
Done.
Searching for "angel" by Black Pumas...
Done.
Searching for "lightweight" by DE'WAYNE...
Done.
Searching for "baby blue" by Dreamer Boy...
Done.
Searching for "all life long" by Conrad Sewell...
Done.
Searching for "zodiac" by Kita Alexander...
Done.
Searching for "stick season" by Walk off the Earth...
Done.
Searching for "who's sorry now?" by ASTON...
Done.
Searching for "easily attached" by Vicki Vox...
Done.
Searching for "over you" by Jacob Collier...
Done.
Searching for "miss me too" by Griff...
Done.
Searching for "me, myself & your eyes" by Knox...
Done.
Searching for "hearts on the run" by Delta Goodrem...
Done.
Searching for "another place" by Tom Frane...
Done.
Searching for "venus" by Zara Larsson...
Done.
Searching for "lead me on" by FLETCHER...
Done.
Searching for "stupid in love" by MAX...
Done.
Searching for "wintergreen" by asiris...
Done.
Searching for "summer after senior year" by Sarah Kang...
Done.
Searching for "i'm fine" by ROZES...
Done.
Searching for "bitter sweet love" by James Arthur...
Done.
Searching for "magic" by Will Linley...
Done.
Searching for "into your room" by Holly Humberstone...
Done.
Searching for "23" by Lawrence...
Done.
Searching for "miracle" by BOYS LIKE GIRLS...
Done.
Searching for "holding on to us" by Leslie Odom Jr....
Done.
Searching for "jealousy" by Spencer Sutherland...
Done.
Searching for "new light" by John Mayer...
Done.
Searching for "modern girl" by Bleachers...
Done.
Searching for "september" by James Arthur...
Done.
Searching for "oh my god" by Adele...
Done.
Searching for "dying on the inside" by Nessa Barrett...
Done.
Searching for "hypotheticals" by Lake Street Dive...
Done.
Searching for "remind me" by Tom Grennan...
Done.
Searching for "somebody to you" by Cody Fry...
Done.
Searching for "all 4 nothing" by Lauv...
Done.
Searching for "i'm good" by David Guetta...
Done.
Searching for "hips don't lie" by Shakira...
Done.
Searching for "dreams" by Fleetwood Mac...
Done.
Searching for "texas hold 'em" by Beyoncé...
Done.
Searching for "closer" by The Chainsmokers...
Done.
Searching for "one kiss" by Calvin Harris...
Done.
Searching for "dance the night" by Dua Lipa...
Done.
Searching for "just give me a reason" by P!nk...
Done.
Searching for "uptown funk" by Mark Ronson...
Done.
Searching for "see you again" by Wiz Khalifa...
Done.
Searching for "we don't talk anymore" by Charlie Puth...
Done.
Searching for "cold heart" by Elton John...
Done.
Searching for "cheerleader" by OMI...
Done.
Searching for "bad guy" by Billie Eilish...
Done.
Searching for "she will be loved" by Maroon 5...
Done.
Searching for "hot hot amore" by Lia Larsson...
Done.
Searching for "små grodorna" by LOOKET...
Done.
Searching for "sommaren i city" by Angel...
Done.
Searching for "bella festa" by De Vet Du...
Done.
Searching for "kalle teodor" by J.O.X...
Done.
Searching for "fulla" by Silje Bakke...
Done.
Searching for "höger vänster" by PERZZONA...
Done.
Searching for "karusellen" by J.O.X...
Done.
Searching for "inget stoppar oss nu" by Dolores...
Done.
Searching for "dunka dunka" by Megic Mike...
Done.
Searching for "f.f.f." by FESTEN...
Done.
Searching for "pärlor" by Dolores...
Done.
Searching for "funny bunny" by demz...
Done.
Searching for "jag vet du vill ha mig" by Perra & Berra...
Done.
Searching for "alla får komma" by FESTEN...
Done.
Searching for "dunka" by JONE...
Done.
Searching for "en gång till" by Hooja...
Done.
Searching for "första biran" by Elov & Beny...
Done.
Searching for "min största första kärlek" by Perra & Berra...
Done.
Searching for "dum i huvet" by Coola Kids...
Done.
Searching for "freaks" by PERZZONA...
Done.
Searching for "när vi två blir en" by Perra & Berra...
Done.
Searching for "kör ba' kör" by PERZZONA...
Done.
Searching for "en kväll i juni" by Louise Andersson Bodin...
Done.
Searching for "kaos" by LBSB...
Done.
Searching for "in med en prilla" by LOOKET...
Done.
Searching for "ack & ve" by Strög1...
Done.
Searching for "weed i raggarbil" by Rasmus Gozzi...
Done.
Searching for "34:an" by Louise Andersson Bodin...
Done.
Searching for "under hökens vingar" by LOOKET...
Done.
Searching for "gammal i gemet" by Hooja...
Done.
Searching for "dansa i neon" by Lena Philipsson...
Done.
Searching for "vi ska aldrig hem" by Mozby...
Done.
Searching for "lavish 2.0" by PERZZONA...
Done.
Searching for "ta en öl" by Maximus...
Done.

,track_name,artist_name,lyrics,track_name_count,word_count,cleaned_track_name
0,No Scrubs,TLC,14 ContributorsTranslationsPortuguêsNo Scrubs ...,0,0,no scrubs
5,Hypnotize - 2007 Remaster,The Notorious B.I.G.,228 ContributorsHypnotize Lyrics[Intro: The No...,0,2,hypnotize
7,What's Luv? (feat. Ja-Rule & Ashanti),Fat Joe,54 ContributorsTranslationsFrançaisWhat’s Luv?...,0,0,what's luv?
9,Crazy In Love (feat. Jay-Z),Beyoncé,122 ContributorsCrazy in Love Lyrics[Intro: JA...,0,1,crazy in love
13,Jenny from the Block (feat. Jadakiss & Styles ...,Jennifer Lopez,39 ContributorsJenny from the Block Lyrics[Int...,0,11,jenny from the block
...,...,...,...,...,...,...
432,GAMMAL I GEMET,Hooja,1 ContributorVem Som Helst Lyrics[Intro]\nHoho...,0,0,gammal i gemet
435,Dansa i neon (N!NE Remix),Lena Philipsson,4 ContributorsDansa I Neon LyricsMitt i en sto...,0,0,dansa i neon
437,Vi ska aldrig hem,Mozby,1 ContributorDen Eviga Vilan LyricsEn stadig g...,0,0,vi ska aldrig hem
439,LAVISH 2.0,PERZZONA,8 ContributorsScarface Script LyricsScarface\n...,0,0,lavish 2.0
443,TA EN ÖL (DOH DAH),Maximus,1 ContributorDu och jag Lyrics-Hallå\n-Sala\n-...,0,0,ta en öl

In [1215]:
trainbus_18 = fetch_lyrics(api, track_name = "99 Problems", artist_name = "JAY-Z")

Searching for "99 Problems" by JAY-Z...
Done.

In [1216]:
trainbus_27 = fetch_lyrics(api, track_name = "My Name Is", artist_name = "Eminem")

Searching for "My Name Is" by Eminem...
Done.

In [1217]:
trainbus_29 = fetch_lyrics(api, track_name = "Independent Women Part I", artist_name = "Destiny's Child")

Searching for "Independent Women Part I" by Destiny's Child...
Done.

In [1218]:
trainbus_234 = fetch_lyrics(api, track_name = "All 4 Nothing (I’m So In Love)", artist_name = "Lauv")

Searching for "All 4 Nothing (I’m So In Love)" by Lauv...
Done.

In [1220]:
nextt.loc[18, 'lyrics'] = trainbus_18
nextt.loc[27, 'lyrics'] = trainbus_27
nextt.loc[29, 'lyrics'] = trainbus_29
nextt.loc[234, 'lyrics'] = trainbus_234

In [1221]:
trainBus.loc[nextt.index, 'lyrics'] = nextt['lyrics']

# Save Cleaned Lyrics Data

In [1222]:
trainBus.to_csv('trainbus_correct_lyrics.csv', index=False)
library.to_csv('library_correct_lyrics.csv', index=False)
mall.to_csv('mall_correct_lyrics.csv', index=False)
bar.to_csv('bar_correct_lyrics.csv', index=False)
gym.to_csv('gym_correct_lyrics.csv', index=False)
bedroom.to_csv('bedroom_correct_lyrics.csv', index=False)
office.to_csv('office_correct_lyrics.csv', index=False)
restaurant.to_csv('restaurant_correct_lyrics.csv', index=False)